### ISSUE TITLE
ModuleNotFoundError: No module named 'pgl.utils.log_writer'

### ISSUE THREAD

**Issue by ZixuanNi** [PaddlePaddle/PGL#103]
when I run examples/deeper_gcn/train.py  shows that"ModuleNotFoundError: No module named 'pgl.utils.log_writer"。And my paddle version is 1.7.2 and PGL version is v1.1

**Comment by Yelrose** [comment]
The new log_writer has not been packaged into the latest PGL wheels. You can manually install pgl by ```git clone``` and ```python setup.py install```.

**Comment by wq343580510** [comment]
/ssd1/wangqi38/tools/python_new/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
g++ -pthread -shared build/temp.linux-x86_64-2.7/pgl/graph_kernel.o -L/home/users/zhouhanqing/python/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/pgl/graph_kernel.so
/home/opt/gcc-4.8.2.bpkg-r4/gcc-4.8.2.bpkg-r4/sbin/../lib/gcc/x86_64-baidu-linux-gnu/4.8.2/../../../../x86_64-baidu-linux-gnu/bin/ld: cannot find -lpython2.7
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1

还是报错 python setup.py  install也不行

**Comment by Yelrose** [comment]
这个主要是python lib设置有问题， -L/home/users/zhouhanqing/python/lib  跟/ssd1/wangqi38/tools/python_new/lib/python2.7/l 路径对不上
