### ISSUE TITLE
pgl 在docker中构建graph报segment fault

### ISSUE THREAD

**Issue by xiuechen** [PaddlePaddle/PGL#105]
报错信息：

W0720 03:52:59.207820  3586 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0720 03:52:59.207885  3586 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0720 03:52:59.207908  3586 init.cc:221] The detail failure signal is:

W0720 03:52:59.207937  3586 init.cc:224] *** Aborted at 1595217179 (unix time) try "date -d @1595217179" if you are using GNU date ***
W0720 03:52:59.209323  3586 init.cc:224] PC: @                0x0 (unknown)
W0720 03:52:59.209501  3586 init.cc:224] *** SIGSEGV (@0x0) received by PID 3586 (TID 0x7f213102e740) from PID 0; stack trace: ***
W0720 03:52:59.210655  3586 init.cc:224]     @     0x7f2130840630 (unknown)
W0720 03:52:59.211284  3586 init.cc:224]     @     0x7f2104830b62 (unknown)
W0720 03:52:59.211845  3586 init.cc:224]     @     0x7f210483390d (unknown)
W0720 03:52:59.213013  3586 init.cc:224]     @     0x7f2130b32300 PyEval_EvalFrameEx
W0720 03:52:59.214179  3586 init.cc:224]     @     0x7f2130b3464d PyEval_EvalCodeEx
W0720 03:52:59.215322  3586 init.cc:224]     @     0x7f2130abe07d (unknown)
W0720 03:52:59.216428  3586 init.cc:224]     @     0x7f2130a99073 PyObject_Call
W0720 03:52:59.217643  3586 init.cc:224]     @     0x7f2130aa8065 (unknown)
W0720 03:52:59.218773  3586 init.cc:224]     @     0x7f2130a99073 PyObject_Call
W0720 03:52:59.219944  3586 init.cc:224]     @     0x7f2130af0097 (unknown)
W0720 03:52:59.221132  3586 init.cc:224]     @     0x7f2130aeedaf (unknown)
W0720 03:52:59.222276  3586 init.cc:224]     @     0x7f2130a99073 PyObject_Call
W0720 03:52:59.223424  3586 init.cc:224]     @     0x7f2130b2d846 PyEval_EvalFrameEx
W0720 03:52:59.224547  3586 init.cc:224]     @     0x7f2130b3464d PyEval_EvalCodeEx
W0720 03:52:59.225683  3586 init.cc:224]     @     0x7f2130abdf88 (unknown)
W0720 03:52:59.226790  3586 init.cc:224]     @     0x7f2130a99073 PyObject_Call
W0720 03:52:59.227934  3586 init.cc:224]     @     0x7f2130a99155 (unknown)
W0720 03:52:59.229049  3586 init.cc:224]     @     0x7f2130a9923e PyObject_CallFunction
W0720 03:52:59.230197  3586 init.cc:224]     @     0x7f2130ad5561 _PyObject_GenericGetAttrWithDict
W0720 03:52:59.231338  3586 init.cc:224]     @     0x7f2130b2f800 PyEval_EvalFrameEx
W0720 03:52:59.232473  3586 init.cc:224]     @     0x7f2130b3464d PyEval_EvalCodeEx
W0720 03:52:59.233608  3586 init.cc:224]     @     0x7f2130b31b4c PyEval_EvalFrameEx
W0720 03:52:59.234735  3586 init.cc:224]     @     0x7f2130b3464d PyEval_EvalCodeEx
W0720 03:52:59.235885  3586 init.cc:224]     @     0x7f2130abe07d (unknown)
W0720 03:52:59.236999  3586 init.cc:224]     @     0x7f2130a99073 PyObject_Call
W0720 03:52:59.238148  3586 init.cc:224]     @     0x7f2130aa8065 (unknown)
W0720 03:52:59.239271  3586 init.cc:224]     @     0x7f2130a99073 PyObject_Call
W0720 03:52:59.240423  3586 init.cc:224]     @     0x7f2130af0097 (unknown)
W0720 03:52:59.241578  3586 init.cc:224]     @     0x7f2130aeedaf (unknown)
W0720 03:52:59.242700  3586 init.cc:224]     @     0x7f2130a99073 PyObject_Call
W0720 03:52:59.243827  3586 init.cc:224]     @     0x7f2130b2d846 PyEval_EvalFrameEx
W0720 03:52:59.244946  3586 init.cc:224]     @     0x7f2130b3464d PyEval_EvalCodeEx
Segmentation fault

测试代码：
import pgl
from pgl import graph  # import pgl module
import numpy as np

edge_list=[]
node_list=[]
filename="./testnode.txt"
#filename="./edgelist.txt"
try:
    fp=open(filename,"r")
    print("%s open succesfully"%filename)
    done=False
    while not done:
        aline=fp.readline();
        if aline!="":
            a=long(aline.strip("\n").strip("(").strip(")").split(",")[0])
            b=long(aline.strip("\n").strip("(").strip(")").split(",")[1])
            edge_list.append((a,b))
            node_list.append(a)
            node_list.append(b)
        else:
            done=True
    fp.close()
except IOError:
     print("%s open failed"%filename)

print type(list)
print(edge_list)
print(node_list)
news_nodes = []

for id in node_list:
    if id not in news_nodes:
        news_nodes.append(id)
num_node=len(news_nodes)
print("%d nodes"%num_node)
print(news_nodes)

#num_node=359625121
d = 8
feature = np.random.randn(num_node, d).astype("float32")
edge_feature = np.random.randn(len(edge_list), d).astype("float32")

g = graph.Graph(num_nodes = num_node,edges = edge_list,node_feat = {'feature':feature},edge_feat ={'edge_feature': edge_feature})

读入的文件内容：
(-4649263633069986650,-5524713781035048896)
(1271252742248293960,5257009004707542774)
(-7235151214169208912,-801785351457387666)
(3878525930642985553,-4845667399646036208)
(3787724060214927072,2498311633260070737)
(-1926501030799233262,-2531193103782375080)
(5379329040149508336,-1753726466388496271)
(-2731878471209782768,7141705257445771183)
(208737387650153426,-4842986495434924796)
(6859451388928841912,-1849683348999068048)
(-5297793359529213911,-730495328556966270)
(-8990674550612404115,5475799282437796300)
(8281941951883016219,2817935382386340348)
(-3531905366784664905,8330449695852382521)

我的paddle版本是:
PaddlePaddle 1.8.3, compiled with
    with_avx: ON
    with_gpu: OFF
    with_mkl: ON
    with_mkldnn: ON
    with_python: ON

python版本2.7.5

**Comment by xiuechen** [comment]
补充一下，这个图的节点id映射好了之后，稍微改造了下，跑node2vec。发现在报除0错误：
具体信息
[INFO] 2020-07-20 06:09:58,135 [ node2vec.py:  314]:    Namespace(batch_size=1024, dataset='/pgl/mypdl/file/testnode.txt', epoch=400, hidden_size=128, neg_num=20, offline_learning=True, p=0.25, processes=10, q=0.25, save_path='./tmp/node2vec_BlogCatalog/', use_cuda=False, walk_len=40, win_size=10)
[INFO] 2020-07-20 06:09:58,136 [ node2vec.py:  225]:    Start random walk on disk...
/pgl/mypdl/file/testnode.txt open succesfully
[INFO] 2020-07-20 06:09:58,191 [ node2vec.py:  235]:    Random walk on disk Done.
2020-07-20 06:09:58,192-WARNING: paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
Traceback (most recent call last):
  File "node2vec.py", line 315, in <module>
    main(args)
  File "node2vec.py", line 249, in main
    lr = l.polynomial_decay(0.025, train_steps, 0.0001)
  File "/usr/lib64/python2.7/site-packages/paddle/fluid/layers/learning_rate_scheduler.py", line 347, in polynomial_decay
    ((1 - global_step / decay_steps) ** power) + end_learning_rate
  File "/usr/lib64/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 201, in __impl__
    return scalar_method(self, float(other_var))
  File "/usr/lib64/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 183, in _scalar_elementwise_div_
    return _scalar_elementwise_op_(var, 1.0 / value, 0.0)
ZeroDivisionError: float division by zero


对应的代码：

303     parser.add_argument("--hidden_size", type=int, default=128)
    304     parser.add_argument("--neg_num", type=int, default=20)
    305     parser.add_argument("--epoch", type=int, default=100)
    306     parser.add_argument("--batch_size", type=int, default=1024)
    307     parser.add_argument("--walk_len", type=int, default=40)
    308     parser.add_argument("--win_size", type=int, default=10)
    309     parser.add_argument("--p", type=float, default=0.25)
    310     parser.add_argument("--q", type=float, default=0.25)
    311     parser.add_argument("--save_path", type=str, default="./tmp/node2vec")
    312     parser.add_argument("--processes", type=int, default=10)
    313     args = parser.parse_args()
    314     log.info(args)
    315     main(args)
-----------

    245     with fluid.program_guard(node2vec_prog, startup_prog):
    246         with fluid.unique_name.guard():
    247             node2vec_pyreader, node2vec_loss = node2vec_model(
    248                 dataset, hidden_size=hidden_size, neg_num=neg_num)
    249             lr = l.polynomial_decay(0.025, train_steps, 0.0001)
    250             adam = fluid.optimizer.Adam(lr)
    251             adam.minimize(node2vec_loss)

**Comment by kirayummy** [comment]
除0报错定位于测试文件过小，节点数少于batch数，导致polynomial_decay内部除0，目前已fix
