### ISSUE TITLE
能否在AIStudio里搞一个运行ErnieSage的项目

### ISSUE THREAD

**Issue by onewaymyway** [PaddlePaddle/PGL#106]
能否在AIStudio里搞一个运行ErnieSage的NoteBook项目
这样就可以方便的在AIStudio里研究ErnieSage的用法了

**Comment by kirayummy** [comment]
ok，我们准备一个

**Comment by kirayummy** [comment]
基于ERNIESage建了一个环境在AIStudio，见：
https://aistudio.baidu.com/aistudio/projectdetail/667443

**Comment by onewaymyway** [comment]
> 基于ERNIESage建了一个环境在AIStudio，见：
> https://aistudio.baidu.com/aistudio/projectdetail/667443

赞！已fork
