### ISSUE TITLE
GATNE的异构节点复现

### ISSUE THREAD

**Issue by edencfc** [PaddlePaddle/PGL#117]
GATNE的示例是同构节点、异构边，好像没找到GATNE在`https://github.com/THUDM/GATNE/tree/master/data`另外三个数据集上异构节点的复现？

**Comment by Liwb5** [comment]
三个数据集的格式基本一样, 可以参照youtube数据集的格式, 训练另外两个数据集.

**Comment by edencfc** [comment]
谢谢，问题已解决！
