### ISSUE TITLE
GATNE例程有个小bug

### ISSUE THREAD

**Issue by zzs95** [PaddlePaddle/PGL#130]
[GATNE/model.py](https://github.com/PaddlePaddle/PGL/blob/main/examples/GATNE/model.py
)

       
    trans_weights = fl.create_parameter(
            shape=[
                self.edge_type_count, self.embedding_u_size,
                self.embedding_size // self.att_head
            ],
            attr=fluid.initializer.TruncatedNormalInitializer(
                loc=0.0, scale=1.0 / math.sqrt(self.embedding_size)),
            dtype='float32',
            name='trans_w')

attr应该是default_initializer 吧

**Comment by Liwb5** [comment]
我看GATNE的作者也是用TruncatedNormalInitializer初始化的呢.

**Comment by zzs95** [comment]
> 我看GATNE的作者也是用TruncatedNormalInitializer初始化的呢.

我的意思是，[create_parameter](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/create_parameter_cn.html#create-parameter)这个api的初始化变量应该是default_initializer，不是attr

应该是就是这样

    trans_weights = fl.create_parameter(
        shape=[
            self.edge_type_count, self.embedding_u_size,
            self.embedding_size // self.att_head
        ],
        **default_initializer**=fluid.initializer.TruncatedNormalInitializer(
            loc=0.0, scale=1.0 / math.sqrt(self.embedding_size)),
        dtype='float32',
        name='trans_w')

要不然就报错

> TypeError: The type of 'attr' in create_parameter must be (<class 'NoneType'>, <class 'paddle.fluid.param_attr.ParamAttr'>), but received <class 'paddle.fluid.initializer.TruncatedNormalInitializer'>. 

attr 输入的应该是属性对象ParamAttr
default_initializer  输入的才是fluid.initializer

**Comment by Liwb5** [comment]
噢噢, 感谢提醒. 我修改一下.

**Comment by zzs95** [comment]
也可以把初始化封装成属性对象，就可以用attr变量传参了
```
import paddle.fluid as fluid
import math
import paddle.fluid.layers as layers
W = layers.create_parameter(shape=[784, 200], dtype='float32',attr=fluid.ParamAttr(initializer=fluid.initializer.MSRAInitializer(uniform=False)))
```
