### ISSUE TITLE
Windows系统下pgl应如何安装

### ISSUE THREAD

**Issue by Li-li-Zhen** [PaddlePaddle/PGL#14]
Windows10系统，paddlepaddle版本1.6.1.post107，cudnn是7.3.1，CDUA是10.0.0，python3.7.5。
在conda命令行中输入pip install pgl，错误提示如下：
![image](https://user-images.githubusercontent.com/53558965/68366141-81dc8f80-016d-11ea-90a3-b575aa8956e5.png)
请问在我上述环境下对应的pgl应该如何安装？

**Comment by Mengyuliu0520** [comment]
+1

**Comment by kirayummy** [comment]
目前PGL暂时还未支持Windows，预计会在未来版本支持。欢迎大家先在Linux/Mac环境下使用。

**Comment by xxllp** [comment]
还不支持啊
