### ISSUE TITLE
pgl.sample deepwalk_sample报错

### ISSUE THREAD

**Issue by xiangfusheng** [PaddlePaddle/PGL#140]
![image](https://user-images.githubusercontent.com/18589429/97988554-1ed11780-1e18-11eb-9f9f-37ecda284595.png)
![image](https://user-images.githubusercontent.com/18589429/97988604-2e506080-1e18-11eb-9398-c5b8f954355b.png)

**Comment by xiangfusheng** [comment]
这事啥原因呢

**Comment by Liwb5** [comment]
deepwalk_sample 只是针对同构图的采样而不是异构图。
