### ISSUE TITLE
PGL手册里Quick Start Instructions例程报错

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/PGL#145]
使用aistudio飞桨 1.7.2 版本：PaddlePaddle 1.7.2
python3.7 

PGL手册里，https://pgl.readthedocs.io/en/latest/quick_start/instruction.html
按照手册里的内容键入notebook，到了这句运行报错：

    output = gcn_layer(gw, gw.node_feat['feature'], gw.edge_feat['edge_feature'],
                    hidden_size=8, name='gcn_layer_1', activation='relu')
    output = gcn_layer(gw, output, gw.edge_feat['edge_feature'],
                    hidden_size=1, name='gcn_layer_2', activation=None)

报错信息：

---------------------------------------------------------------------------KeyError                                  Traceback (most recent call last)<ipython-input-14-07a77fc8d914> in <module>
----> 1 output = gcn_layer(gw, gw.node_feat['feature'], gw.edge_feat['edge_feature'],
      2                 hidden_size=8, name='gcn_layer_1', activation='relu')
      3 output = gcn_layer(gw, output, gw.edge_feat['edge_feature'],
      4                 hidden_size=1, name='gcn_layer_2', activation=None)
KeyError: 'edge_feature'

后来看了一下，print(gw.edge_feat) 显示为{} 
g.node_feat_info() 显示为[('feature', [None, 16], dtype('float32'))]

**Comment by Liwb5** [comment]
这个问题应该是在构建GraphWrapper的时候, 没有指定edge_feat. 这个bug在github的tutorials已经修改了。
可以参考这里： https://github.com/PaddlePaddle/PGL/blob/main/tutorials/1-Introduction.ipynb
`
gw = pgl.graph_wrapper.GraphWrapper(name='graph',
                place = place,
                node_feat=g.node_feat_info(),
                edge_feat=g.edge_feat_info())
`
抱歉 quick_start 的文档还没有及时更新，我们这边会尽快更新。

**Comment by skywalk163** [comment]
感谢及时准确的解答。
