### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/PGL#152]
win10 Platform
paddle 1.8.5
![Z)1R%)1~I88%66OGGV_NO94](https://user-images.githubusercontent.com/49911294/100074279-84458080-2e79-11eb-87f2-a34ca51e7702.png)

**Comment by ZHUI** [comment]
Thanks, we fixed it in https://github.com/PaddlePaddle/PGL/pull/149 .
