### ISSUE TITLE
关于分布式版本部署的问题

### ISSUE THREAD

**Issue by hhh920406** [PaddlePaddle/PGL#16]
PGL的分布式版本可以在哪些平台上部署呢？有分布式版本PGL的部署指引可以提供吗？example中提供的deepwalk及graphsage的分布式版本的运行环境可以详细说明下吗？

**Comment by kirayummy** [comment]
1. examples/distribute_graphsage里展示了一个分布式图引擎的demo，目前这块只是一个示例用redis搭建的图引擎，可以让你通过图引擎进行采样训练GraphSAGE。如果想自己定制化图，可以参照一下docker里面图灌库以及启动server的代码。这部分的描述我们后续会继续完善。

2. examples/distribute_deepwalk里展示了一个分布式训练deepwalk模型的demo，基于paddle的fleet分布式计算引擎，通过修改pgl_deepwalk.cfg可以自定义模型的超参数，以cloud_run.sh
脚本为例，展示了一个单机多端口模拟多机训练的例子，在真实多机训练中可根据这里例子修改。
