### ISSUE TITLE
erniesage的例子

### ISSUE THREAD

**Issue by HaoRan98** [PaddlePaddle/PGL#166]
用python ./preprocessing/dump_graph.py  --conf='./config/erniesage_link_predict.yaml'运行后，报错：

  Traceback (most recent call last):
  File "./preprocessing/dump_graph.py", line 221, in <module>
    dump_node_feat(config)
  File "./preprocessing/dump_graph.py", line 185, in dump_node_feat
    tokenizer = ErnieTinyTokenizer.from_pretrained(config.ernie_name)
  File "/home/alphis/ws/pei_zhi_huan_jing/ERNIE/ernie/tokenizing_ernie.py", line 223, in from_pretrained
    t = cls(vocab_dict, sp_model_path, **kwargs)
  File "/home/alphis/ws/pei_zhi_huan_jing/ERNIE/ernie/tokenizing_ernie.py", line 232, in __init__
    self.sp_model.Load(sp_model_path)
  File "/home/alphis/anaconda3/envs/nlp/lib/python3.7/site-packages/sentencepiece/__init__.py", line 367, in Load
    return self.LoadFromFile(model_file)
  File "/home/alphis/anaconda3/envs/nlp/lib/python3.7/site-packages/sentencepiece/__init__.py", line 171, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string

**Comment by selinplus** [comment]
change config/erniesage_link_predict.yaml'
ernie_name: "ernie-1.0"
#ernie_name: "ernie-tiny"
suspend ernie no ernie-tiny model

**Comment by HaoRan98** [comment]
Thanks
但是又出现了新的错误
Traceback (most recent call last):
  File "link_predict.py", line 272, in <module>
    predict(config)
  File "link_predict.py", line 230, in predict
    predict_ds = Dataset.from_generator_func(predict_iter)
  File "/home/alphis/ws/pei_zhi_huan_jing/ERNIE/propeller/data/functional.py", line 278, in from_generator_func
    raise ValueError('expect generator function, got %s' % repr(_gen))
还是配置文件的问题么？

**Comment by selinplus** [comment]
same error on my machine

**Comment by WeiyueSu** [comment]
更新一下pip install -U paddle-propeller，升级为最新版本

**Comment by HaoRan98** [comment]
@WeiyueSu 
可以用了，但是又出现了新的问题。。
我运行的是erniesage中link_predict的例子，config.epochs设置的3，但是每次训练跑了20步就停了，
[DEBUG] 2020-12-29 15:47:57,471 [monitored_executor.py:  199]:  saving step 21 to ./output/model_21

**Comment by HaoRan98** [comment]
@WeiyueSu 
而且没有生成last文件

**Comment by FallBlackMagic** [comment]
你好，我在运行示例的时候遇到以下错误，
paddle版本：2.0.0rc 
pgl版本：1.2.1
---------------------------------------------------------------------------AttributeError                            Traceback (most recent call last)<ipython-input-17-af810e570477> in <module>
     11         inputs = L.data("inputs", [2], False, 'int64')
     12 
---> 13         gw = BatchGraphWrapper(num_nodes, num_edges, edges, {"term_ids": node_feat})
     14         outputs = erniesage_v2_encoder([gw], [inputs])
     15 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pgl/graph_wrapper.py in __init__(self, num_nodes, num_edges, edges, node_feats, edge_feats)
    829         self._edge_uniq_dst_count = L.concat([uniq_count, last])
    830         self._edge_uniq_dst_count.stop_gradient = True
--> 831         self._indegree = get_degree(self._edges_dst, self._num_nodes)
    832 
    833     def __build_meta_data(self, num_nodes, num_edges):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pgl/graph_wrapper.py in get_degree(edge, num_nodes)
    729         init_output,
    730         edge,
--> 731         L.full_like(
    732             edge, 1, dtype="float32"),
    733         overwrite=False)
AttributeError: module 'paddle.fluid.layers' has no attribute 'full_like'

请问这得怎么解决呀？

**Comment by ZHUI** [comment]
> 你好，我在运行示例的时候遇到以下错误，
> paddle版本：2.0.0rc
> pgl版本：1.2.1
> ---------------------------------------------------------------------------AttributeError Traceback (most recent call last) in
> 11 inputs = L.data("inputs", [2], False, 'int64')
> 12
> ---> 13 gw = BatchGraphWrapper(num_nodes, num_edges, edges, {"term_ids": node_feat})
> 14 outputs = erniesage_v2_encoder([gw], [inputs])
> 15
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pgl/graph_wrapper.py in **init**(self, num_nodes, num_edges, edges, node_feats, edge_feats)
> 829 self._edge_uniq_dst_count = L.concat([uniq_count, last])
> 830 self._edge_uniq_dst_count.stop_gradient = True
> --> 831 self._indegree = get_degree(self._edges_dst, self._num_nodes)
> 832
> 833 def __build_meta_data(self, num_nodes, num_edges):
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pgl/graph_wrapper.py in get_degree(edge, num_nodes)
> 729 init_output,
> 730 edge,
> --> 731 L.full_like(
> 732 edge, 1, dtype="float32"),
> 733 overwrite=False)
> AttributeError: module 'paddle.fluid.layers' has no attribute 'full_like'
> 
> 请问这得怎么解决呀？

同学您好，基于PGL 2.0全新动态图版本，PaddleNLP将erniesage迁移至动态图。欢迎试用动态图版本，更加方便debug，更易用。
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_graph/erniesage 
同时，PGL的erniesage 2.0也在开发中，敬请期待。

**Comment by randomtutu** [comment]
一点都不简单可依赖，楼主咨询报错，回复让试试2.0。

**Comment by randomtutu** [comment]
> 你好，我在运行示例的时候遇到以下错误，
> paddle版本：2.0.0rc
> pgl版本：1.2.1
> ---------------------------------------------------------------------------AttributeError Traceback (most recent call last) in
> 11 inputs = L.data("inputs", [2], False, 'int64')
> 12
> ---> 13 gw = BatchGraphWrapper(num_nodes, num_edges, edges, {"term_ids": node_feat})
> 14 outputs = erniesage_v2_encoder([gw], [inputs])
> 15
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pgl/graph_wrapper.py in **init**(self, num_nodes, num_edges, edges, node_feats, edge_feats)
> 829 self._edge_uniq_dst_count = L.concat([uniq_count, last])
> 830 self._edge_uniq_dst_count.stop_gradient = True
> --> 831 self._indegree = get_degree(self._edges_dst, self._num_nodes)
> 832
> 833 def __build_meta_data(self, num_nodes, num_edges):
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pgl/graph_wrapper.py in get_degree(edge, num_nodes)
> 729 init_output,
> 730 edge,
> --> 731 L.full_like(
> 732 edge, 1, dtype="float32"),
> 733 overwrite=False)
> AttributeError: module 'paddle.fluid.layers' has no attribute 'full_like'
> 
> 请问这得怎么解决呀？

paddle1.7没有这个api，升级1.8及其以上就可以了。主页上的依赖有一点问题。

**Comment by l-i-p-f** [comment]
> 你好，我在运行示例的时候遇到以下错误， paddle版本：2.0.0rc pgl版本：1.2.1 ---------------------------------------------------------------------------AttributeError Traceback (most recent call last) in 11 inputs = L.data("inputs", [2], False, 'int64') 12 ---> 13 gw = BatchGraphWrapper(num_nodes, num_edges, edges, {"term_ids": node_feat}) 14 outputs = erniesage_v2_encoder([gw], [inputs]) 15 /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pgl/graph_wrapper.py in **init**(self, num_nodes, num_edges, edges, node_feats, edge_feats) 829 self._edge_uniq_dst_count = L.concat([uniq_count, last]) 830 self._edge_uniq_dst_count.stop_gradient = True --> 831 self._indegree = get_degree(self._edges_dst, self._num_nodes) 832 833 def __build_meta_data(self, num_nodes, num_edges): /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pgl/graph_wrapper.py in get_degree(edge, num_nodes) 729 init_output, 730 edge, --> 731 L.full_like( 732 edge, 1, dtype="float32"), 733 overwrite=False) AttributeError: module 'paddle.fluid.layers' has no attribute 'full_like'
> 
> 请问这得怎么解决呀？

参考[Paddle 1.8 与 Paddle 2.0 API映射表](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/08_api_mapping/paddle_api_mapping_cn.html)
新版本api有变动，你用的2.x版本，可以改报错文件的源码，将：
```
L.full_like(
```
改为：
```
import paddle
paddle.full_like(
```
