### ISSUE TITLE
erniesage example raise generator wrong

### ISSUE THREAD

**Issue by selinplus** [PaddlePaddle/PGL#167]
Traceback (most recent call last):
  File "link_predict.py", line 274, in <module>
    train(config)
  File "link_predict.py", line 169, in train
    train_ds = Dataset.from_generator_func(train_iter).repeat(config.epochs)
  File "/home/alphis/ws/pei_zhi_huan_jing/ERNIE/propeller/data/functional.py", line 278, in from_generator_func
    raise ValueError('expect generator function, got %s' % repr(_gen))

**Comment by WeiyueSu** [comment]
try update the propelller by `python -m pip install -U paddle-propeller`

**Comment by HaoRan98** [comment]
@WeiyueSu 
Updata paddle-propeller is not making it work

**Comment by WeiyueSu** [comment]
It seem that you use an old version propeller in `ERNIE` directory. Don't use it. Try use propeller install by pip, or just comment out `"/home/alphis/ws/pei_zhi_huan_jing/ERNIE/propeller/data/functional.py", line 278`
