### ISSUE TITLE
大规模图分析的实践方法

### ISSUE THREAD

**Issue by luotongml** [PaddlePaddle/PGL#168]
我们目前有几千万的节点，过亿条变，进行图分析（node classification/link prediction）如何进行比较好。
1. 图数据需要从图数据库中导出吗？
2. 这种规模的图分析如何有效地进行？
3. 一些节点信息额增加或者属性的变化，如何高效、增量地进行？

**Comment by kirayummy** [comment]
1. 需要导出
2. 可以通过图采样的方式进行图分析，如GraphSage方法
3. 可以将节点信息增加、属性变化表示成特征？

**Comment by illcat** [comment]
> 1. 需要导出
> 2. 可以通过图采样的方式进行图分析，如GraphSage方法
> 3. 可以将节点信息增加、属性变化表示成特征？

原图无法加载，又如何采样？

**Comment by iou2much** [comment]
@kirayummy 请问，对大规模的图，也需要在训练前build graph吗? 节点和边能不能动态地在训练过程中加载?
