### ISSUE TITLE
Unsupervised GraphSAGE 结果

### ISSUE THREAD

**Issue by zhuchuanshuai** [PaddlePaddle/PGL#17]
PGL/examples/unsup_graphsage下运行python train.py --data_path ./sample.txt --num_nodes 2000 --phase predict， 出来的emb.npy文件里是多个embedding结果。

这个结果怎么和sample.txt中的id一一对应起来？第n行的embedding结果对应id=n的embedding吗？但是没有1164这个id，emb.npy文件第1164行却有embedding结果。

**Comment by kirayummy** [comment]
"python train.py --data_path ./sample.txt --num_nodes 2000 --phase predict" 

1. 这里指定了 num_nodes为2000，表示节点数最大为2000，Embedding空间由这个数来定义大小
2. sample.txt指定的是边的src和dst，保证index在2000以内即可

所以即使没在sample.txt出现的id，也会初始化一个随机Embedding，作为一个孤立的点存在，不参与模型训练。

**Comment by zhuchuanshuai** [comment]
1. 第n行的embedding结果对应id=n的embedding对吧？
2. 怎么加入节点特征？

**Comment by zhuchuanshuai** [comment]
3. 怎么使用边的权重？

**Comment by githubutilities** [comment]
1. 第n行的embedding结果对应id=n-1的embedding，id是从0开始编号的
2. 节点特征需要两个步骤：
	1. 在pgl.graph_wrapper.GraphWrapper里面给定参数node_feat，例如：node_feat为`[('index', [-1, 1], np.dtype('int64'))]`，`'index'`为node_feat名字，`[-1, 1]`为node_feat的shape，`np.dtype('int64')`为node_feat的类型
	2. 在`reader.py`里面的subgraph把node_feat挂载上去，例如：`subgraph.node_feat["index"] = np.array([1,2,3], dtype="int64")`
3. 暂时不支持边权重采样
