### ISSUE TITLE
输入图为多通道如何实现？

### ISSUE THREAD

**Issue by waaaaaaater** [PaddlePaddle/PGL#173]
在神经网络中，输入数据可以是多张图片等。
请问在PGL中，是否允许在一个模型中传输进入多个图，并且多个图的size还不一样呢？

**Comment by Liwb5** [comment]
PGL可以允许在一个模型一次传入多张图的. 具体可以参考这个图分类任务的 [示例](https://github.com/PaddlePaddle/PGL/tree/main/examples/gin).

**Comment by waaaaaaater** [comment]
收到，谢谢
