### ISSUE TITLE
请问pinSage在什么地方呢？

### ISSUE THREAD

**Issue by wxf0701** [PaddlePaddle/PGL#175]
请问pinSage在什么地方呢？

**Comment by kirayummy** [comment]
PGL下周发布正式支持paddle 2.0的版本，预计会发布PinSage

**Comment by Andy1314Chen** [comment]
![image](https://user-images.githubusercontent.com/18392483/113674424-c2d32d80-96ec-11eb-825f-8ce045ff1b52.png)

嗯...  pinSAGE啥时候能加进来呢😂

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PGL/pull/203 可以先拿PR使用，我这边尽快推动合入
