### ISSUE TITLE
distribute_deepwalk的问题：offset is too big

### ISSUE THREAD

**Issue by nlj0011** [PaddlePaddle/PGL#19]
您好，在跑distribute_deepwalk的训练阶段时提示offset is too big，然后训练中断。请问这个要怎么修改呀，多谢了~  paddle的版本是1.6，以下是server具体的报错信息。
terminate called after throwing an instance of 'Xbyak::Error'
  what():  offset is too big
W1212 15:27:18.687328 19979 init.cc:212] *** Aborted at 1576135638 (unix time) try "date -d @1576135638" if you are using GNU date ***
W1212 15:27:18.690397 19979 init.cc:212] PC: @                0x0 (unknown)
W1212 15:27:18.690459 19979 init.cc:212] *** SIGABRT (@0x1f400003fd1) received by PID 16337 (TID 0x7f38bbfff700) from PID 16337; stack trace: ***
W1212 15:27:18.693048 19979 init.cc:212]     @     0x7f3ac3ba5160 (unknown)
W1212 15:27:18.695641 19979 init.cc:212]     @     0x7f3ac31133f7 __GI_raise
W1212 15:27:18.698221 19979 init.cc:212]     @     0x7f3ac31147d8 __GI_abort
W1212 15:27:18.699606 19979 init.cc:212]     @     0x7f3a65bdbc65 __gnu_cxx::__verbose_terminate_handler()
W1212 15:27:18.700861 19979 init.cc:212]     @     0x7f3a65bd9e06 __cxxabiv1::__terminate()
W1212 15:27:18.702225 19979 init.cc:212]     @     0x7f3a65bd9e33 std::terminate()
W1212 15:27:18.703485 19979 init.cc:212]     @     0x7f3a65c2c935 execute_native_thread_routine
W1212 15:27:18.705993 19979 init.cc:212]     @     0x7f3ac3b9d1c3 start_thread
W1212 15:27:18.708621 19979 init.cc:212]     @     0x7f3ac31c512d __clone
W1212 15:27:18.711194 19979 init.cc:212]     @                0x0 (unknown)

另外worker有一处报错为PaddleCheckError: Expected posix_memalign(&p, alignment, size) == 0, but received posix_memalign(&p, alignment, size):12 != 0:0.

**Comment by WeiyueSu** [comment]
paddle可以升到最新的1.6.1试试，请问用了多少节点的图呢？暂时没复现到这问题

**Comment by nlj0011** [comment]
> paddle可以升到最新的1.6.1试试，请问用了多少节点的图呢？暂时没复现到这问题

现在用的是1.6.0，有400w节点。用默认dim=128的话会有这个问题，改为dim=32后暂时先能跑了。。是内存不足的原因么？

**Comment by WeiyueSu** [comment]
多机训练内存不足的时候，可以尝试把is_distributed打开的。

**Comment by nlj0011** [comment]
> 训练内存不足的时候，可以尝试把is_distributed打开的。

在pgl_config文件里面吧is_distribute改为True后，会有这个报错PaddleCheckError: Expected ids_dims[0].size() == 2, but received ids_dims[0].size():3 != 2:2.  为False的话是没有问题的。。请问这个怎么修改呀
