### ISSUE TITLE
pgl2.1 centos支持

### ISSUE THREAD

**Issue by Noisyntrain** [PaddlePaddle/PGL#191]
CentOS release 6.3 (Final) 无法使用pgl 2.1 的whl包安装. 我查看了一下, 猜测是因为2.1的whl包是基于manylinux2014打包的, 而之前基于manylinux1打包的2.0a是可以的. 想问一下后续的linux版本都会使用manylinux2014打包么, 以及如果我想在目前这台Centos 上安装pgl2.1 是不是需要自己下载源码编译安装? 谢谢!

**Comment by Noisyntrain** [comment]
另外, 有没有文档说明一下2.0.0a0和2.1的区别 以及2.1同1.2的api变更, 我想要将项目从pgl1.2 转到pgl 2.1 如果有文档可以参考的话会方便很多, 谢谢

**Comment by Yelrose** [comment]
谢谢，目前已重新基于manyliux1 打包pgl，已可在pypi下载
