### ISSUE TITLE
不同节点特征维度不同如何处理

### ISSUE THREAD

**Issue by mylovecc2020** [PaddlePaddle/PGL#195]
您好，我在用PGL解决传感器分类问题建模时遇到了困惑，麻烦问一下图神经网络中如果部分节点特征维度不同，或者某些节点压根就没有特征，这种弄情况下除了采用异质图以外还有其他的方案么？另外我理解同质体不同的节点特征维度必须要相同吧，这个理解对么？谢谢！

**Comment by Yelrose** [comment]
这个的话最好还是用异质网络来做会方便些
