### ISSUE TITLE
关于调用pgl.Graph.tensor()后计算adj_dst_index报错的问题

### ISSUE THREAD

**Issue by lzl19971215** [PaddlePaddle/PGL#196]
您好，我在使用`pgl.Graph`构建一个存储为`numpy.ndarray`的图数据之后，调用`.tensor()`方法将图中的ndarray转换为`paddle.Tensor`时，会报出如下错误：

![7ed401e7daa7b83fe3d8806fc272864](https://user-images.githubusercontent.com/63151530/110887205-d5905780-8324-11eb-873f-e60d1406a27f.png)

进一步观察发现，没转换为tensor之前的Graph中是包含adj_dst_index属性的

![df3f6f1a8c098742441ce290220c508](https://user-images.githubusercontent.com/63151530/110886660-f99f6900-8323-11eb-916a-fc3049b304aa.png)

然而转换之后，在计算这个属性的degree属性时，paddle.scatter()会报错
![226174205fb2b77a9c8364a464991f0](https://user-images.githubusercontent.com/63151530/110886843-3f5c3180-8324-11eb-8b48-cea434feb4e3.png)

同时还发现，如果我分两次分别执行创建Graph以及Graph.tensor()转换(例如在ipython中单步执行两次)，那么转换不会出问题；如果我将这两步操作一起执行，那么在计算adj_dst_index时就会出错。

**Comment by Yelrose** [comment]
你好，能发一下代码执行流程吗？

**Comment by lzl19971215** [comment]
好的
```
    def rna2graph(sequence, pair, dot):
        edges = []

        # add neighbour
        for i in range(len(sequence)):
            edges.append((i, i + 1))
            edges.append((i + 1, i))

        # add pair
        for each in pair:
            edges.append(each)
            edges.append((each[1], each[0]))

        # add self loop
        for i in range(len(sequence)):
            edges.append((i, i))

        num_nodes = len(sequence)
        edges_attr = np.array([0] * (2 * len(sequence)) + [1] * (2 * len(pair)) + [2] * len(sequence)).reshape(-1, 1)
        seq_dic = {k: v for v, k in enumerate(['A', 'C', 'G', 'U'])}
        dot_dic = {k: v for v, k in enumerate(['.', '(', ')'])}
        node_attr = np.array([seq_dic[c] for c in sequence]).reshape(-1, 1)
        dot_attr = np.array([dot_dic[c] for c in dot]).reshape(-1, 1)
        graph = pgl.graph.Graph(edges=edges, num_nodes=num_nodes, node_feat={'one_hot_seq_feature': node_attr,
                                                                             'one_hot_dot_feature': dot_attr},
                                edge_feat={'one_hot_feature': edges_attr})
        return graph
    
    graph = rna2graph(seq_list[0], pair_list[0], dot_list[0])
    graph.tensor()
```
如果把最后两行一起执行的话就会出问题

**Comment by Yelrose** [comment]
> 好的
> 
> ```
>     def rna2graph(sequence, pair, dot):
>         edges = []
> 
>         # add neighbour
>         for i in range(len(sequence)):
>             edges.append((i, i + 1))
>             edges.append((i + 1, i))
> 
>         # add pair
>         for each in pair:
>             edges.append(each)
>             edges.append((each[1], each[0]))
> 
>         # add self loop
>         for i in range(len(sequence)):
>             edges.append((i, i))
> 
>         num_nodes = len(sequence)
>         edges_attr = np.array([0] * (2 * len(sequence)) + [1] * (2 * len(pair)) + [2] * len(sequence)).reshape(-1, 1)
>         seq_dic = {k: v for v, k in enumerate(['A', 'C', 'G', 'U'])}
>         dot_dic = {k: v for v, k in enumerate(['.', '(', ')'])}
>         node_attr = np.array([seq_dic[c] for c in sequence]).reshape(-1, 1)
>         dot_attr = np.array([dot_dic[c] for c in dot]).reshape(-1, 1)
>         graph = pgl.graph.Graph(edges=edges, num_nodes=num_nodes, node_feat={'one_hot_seq_feature': node_attr,
>                                                                              'one_hot_dot_feature': dot_attr},
>                                 edge_feat={'one_hot_feature': edges_attr})
>         return graph
>     
>     graph = rna2graph(seq_list[0], pair_list[0], dot_list[0])
>     graph.tensor()
>     graph.adj_dst_index
> ```
> 
> 如果把最后三行一起执行的话就会出问题
> ![3e118179285093a4cb7c8a089d27683](https://user-images.githubusercontent.com/63151530/110889602-7123c700-8329-11eb-872e-8d7217c39355.png)

你这个可以先检查一下，你的边是否跃界了，边的id是要 < num_nodes的，这块我们后面补充一些异常处理。前面说的那个no attributed的问题，我们已经定位，目前正在修复，可以关注一下后续的Pull Request.

**Comment by lzl19971215** [comment]
好的，这个我也检查过了，边的id应该是没有越界
![f0492eb2c2a96aaddc24388455c0ae9](https://user-images.githubusercontent.com/63151530/110893310-ae3f8780-8330-11eb-97b0-b47da8e66b2f.png)

**Comment by lzl19971215** [comment]
检查了一下，边的确有越界，这个报错信息的索引是从1开始的，我理解成是从0开始的了，非常感谢

**Comment by lzl19971215** [comment]
检查了一下，边的确有越界，非常感谢！

**Comment by Yelrose** [comment]
你可以重新pip install 新的包，应该修复了你的问题了，感谢反馈
