### ISSUE TITLE
status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:

### ISSUE THREAD

**Issue by shuxinyin** [PaddlePaddle/PGL#205]
在distribute_metapath2vec项目里，换成别的的数据，sgd模式能跑的很好，就是loss下降很慢，而将optimizer从sgd换成adam就会报如上错？？
另外，为什么在此例子里，sgd模式lr＝lr✖️real_batchsize?导致刚开始的lr极大，很容易loss爆炸，这么写的原因是什么呢？？

**Comment by Liwb5** [comment]
用Adam可能是有问题的. 分布式的优化器sgd也是有点问题, lr要比较大才能训得动. 你先用sgd的吧. 我们现在在更新动态图版本(2.0以上),后续会比较方便用.

**Comment by shuxinyin** [comment]
是的，sgd这个问题导致distribute_metapath2vec极难训练，请问，分布式里adam的出现这个问题是什么原因呢？是跟数据规模有关，还是目前本身这个实现不够完善导致不可控呢？？

**Comment by Liwb5** [comment]
可以看看这个issue: https://github.com/PaddlePaddle/Paddle/issues/23225 , 或许有帮助.
