### ISSUE TITLE
希望加入无监督的例子

### ISSUE THREAD

**Issue by illcat** [PaddlePaddle/PGL#208]

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/issues/151#issuecomment-800938818

**Comment by Yelrose** [comment]
会的，但是概率非常小。现在主流也有很多人这么用，你可以查一下In-Batch Negative和Cross-Batch Negative的相关论文。

**Comment by illcat** [comment]
> In-Batch Negativ

十分感谢
