### ISSUE TITLE
请问PGL框架进行分布式训练采用的是Parameter Server架构还是ring-AllReduce啊

### ISSUE THREAD

**Issue by Ljl-Jdsk** [PaddlePaddle/PGL#23]
请问PGL框架进行分布式训练采用的是Parameter Server架构还是ring-AllReduce啊

感谢回复

**Comment by Yelrose** [comment]
PGL使用paddle fleet作为参数服务器，目前我们examples里面主要是Parameter Server的架构。

**Comment by Ljl-Jdsk** [comment]
再请问一下PS架构是同步还是异步的呢，异步对于梯度延迟有相应的优化补偿机制吗？

**Comment by Yelrose** [comment]
目前我们提供的示例是异步的，暂时没有优化补偿机制。我们的参数服务器配置这块可以参照一下Paddle Fleet，那边提供很多种模式可以参考。https://github.com/PaddlePaddle/Fleet

**Comment by Ljl-Jdsk** [comment]
感谢分享，对于同步和异步，请问有调研或者测试过效率和效果吗？我数据量比较大，在纠结用同步还是异步，感觉各有优缺点，您推荐使用哪种方式呢

**Comment by kirayummy** [comment]
数据量可以用异步，收敛是能保证的
