### ISSUE TITLE
请问这个是什么问题呢，麻烦帮忙看一下，感谢！ModuleNotFoundError: No module named 'paddle.nn'

### ISSUE THREAD

**Issue by wmingdao** [PaddlePaddle/PGL#232]
TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;Traceback (most recent call last):
  File "/media/dell/TOSHIBA/Fuxian/PGL/ogb_examples/nodeproppred/unimp/main_arxiv.py", line 4, in <module>
    import pgl
  File "/media/dell/TOSHIBA/Fuxian/PGL/pgl/__init__.py", line 23, in <module>
    from pgl import nn
  File "/media/dell/TOSHIBA/Fuxian/PGL/pgl/nn/__init__.py", line 17, in <module>
    from pgl.nn import conv
  File "/media/dell/TOSHIBA/Fuxian/PGL/pgl/nn/conv.py", line 19, in <module>
    import paddle.nn as nn
ModuleNotFoundError: No module named 'paddle.nn'

**Comment by Yelrose** [comment]
Your pgl version is higher than 2.0. Please downgrade to pgl==1.2.1 to run UniMP.

**Comment by DMW123** [comment]
> Your pgl version is higher than 2.0. Please downgrade to pgl==1.2.1 to run UniMP.

我的paddle==1.8.5，pgl==1.2.1。但是还是出现上述问题。ModuleNotFoundError: No module named 'paddle.nn'。不太明白问题到底处在哪里

**Comment by Yelrose** [comment]
>   import pgl
>   File "/media/dell/TOSHIBA/Fuxian/PGL/pgl/**init**.py", line 23, in 
>   from pgl import nn
>   File "/media/dell/TOSHIBA/Fuxian/PGL/pgl/nn/**init**.py", line 17, in 
>   from pgl.nn import conv
>   File "/media/dell/TOSHIBA/Fuxian/PGL/pgl/nn/conv.py", line 19, in 
>   import paddle.nn as nn
>   ModuleNotFoundError: No module named 'paddle.nn'


你import的路径，并不是pip 安装的路径，你应该是在 /media/dell/TOSHIBA/Fuxian/PGL/这个目录底下执行的代码，搜索package有问题。建议你直接在/media/dell/TOSHIBA/Fuxian/PGL/ogb_examples/nodeproppred/unimp/ 这里底下执行。

**Comment by DMW123** [comment]
> > import pgl
> > File "/media/dell/TOSHIBA/Fuxian/PGL/pgl/**init**.py", line 23, in
> > from pgl import nn
> > File "/media/dell/TOSHIBA/Fuxian/PGL/pgl/nn/**init**.py", line 17, in
> > from pgl.nn import conv
> > File "/media/dell/TOSHIBA/Fuxian/PGL/pgl/nn/conv.py", line 19, in
> > import paddle.nn as nn
> > ModuleNotFoundError: No module named 'paddle.nn'
> 
> 你import的路径，并不是pip 安装的路径，你应该是在 /media/dell/TOSHIBA/Fuxian/PGL/这个目录底下执行的代码，搜索package有问题。建议你直接在/media/dell/TOSHIBA/Fuxian/PGL/ogb_examples/nodeproppred/unimp/ 这里底下执行。

好的，我再试试。谢谢您的解答。
