### ISSUE TITLE
GATNE-多维特征如何处理

### ISSUE THREAD

**Issue by zing1116** [PaddlePaddle/PGL#237]
您好，打扰了，我阅读并运行了您的GATNE代码，发现您的数据节点的特征是根据节点的index生成的，所以我想请问一下如果节点含有多维特征，应该如何处理并输入进模型中呢？

**Comment by Liwb5** [comment]
目前示例中没有加入节点特征。如果要加的话，需要自己修改代码，把特征加进去。后面我们会在动态图上更新，加入节点特征。
