### ISSUE TITLE
采样某个节点的全部一阶邻居怎么实现？

### ISSUE THREAD

**Issue by illcat** [PaddlePaddle/PGL#242]

**Comment by illcat** [comment]
您好，我使用的是 graphsage_sample 这个API
https://github.com/PaddlePaddle/PGL/blob/main/pgl/sampling/sage.py#L53

**Comment by kirayummy** [comment]
graphsage_sample这个函数的输入是一个graph，输出是根据samples来采样出subgraphs。
如果你这边的目的是采样1阶的所有邻居，其实不需要过graphsage_sample，原来的graph就是采样了全部一阶邻居

**Comment by illcat** [comment]
> graphsage_sample这个函数的输入是一个graph，输出是根据samples来采样出subgraphs。
> 如果你这边的目的是采样1阶的所有邻居，其实不需要过graphsage_sample，原来的graph就是采样了全部一阶邻居

采样部分节点的全部一节邻居生成子图，所以还是要用到graphsage_sample的

**Comment by kirayummy** [comment]
那可以改下graphsage_sample里的逻辑：
https://github.com/PaddlePaddle/PGL/blob/e8975315e1719d4e574d6527be7042b0c51d7da2/pgl/sampling/sage.py#L81
graph.sample_predecessor  ->  graph.predecessor
-----------------------------------
        batch_pred_nodes, batch_pred_eids = graph.sample_predecessor(
            start_nodes, samples[layer_idx], return_eids=True)
-> 
        batch_pred_nodes, batch_pred_eids = graph.predecessor(
            start_nodes, return_eids=True)

**Comment by illcat** [comment]
> layer_idx

十分感谢。但觉得这里可以重写一下。如果采样个数是-1或者0调用graph.predecessor，正数则调用graph.sample_predecessor.
是不是更好？

**Comment by kirayummy** [comment]
嗯，谢谢！我们考虑一下。:)
