### ISSUE TITLE
How to cite PGL?

### ISSUE THREAD

**Issue by cthoyt** [PaddlePaddle/PGL#245]
Is there a reference publication? Otherwise, you could try using the Zenodo integration with github to get a DOI for the next release you make (via the tags system in git)

**Comment by kirayummy** [comment]
Thank you for your advice. One can cite PGL via

@misc{PGL2021,
    title={Paddle Graph Learning (PGL), an efficient and flexible graph learning framework based on PaddlePaddle},
    author={PaddlePaddle Authors},
    howpublished = {\url{https://github.com/PaddlePaddle/PGL}},
    year={2021}
}

Thanks
PGL Team
