### ISSUE TITLE
MAG240M

### ISSUE THREAD

**Issue by almyprincess** [PaddlePaddle/PGL#249]
In PGL/ogb_examples/lsc/MAG240M demo I can not find the predict code,
so whether there is code to predict the result？
Thanks!

**Comment by Yelrose** [comment]
Thanks for reminding. @sys1874 please check this.

**Comment by Yelrose** [comment]
> In PGL/ogb_examples/lsc/MAG240M demo I can not find the predict code,
> so whether there is code to predict the result？
> Thanks!

The prediction code is provided now. Please check the latest code.

**Comment by almyprincess** [comment]
Thanks a lot ！Wish you all the best in your work~
