### ISSUE TITLE
out of memory error 

### ISSUE THREAD

**Issue by almugabo** [PaddlePaddle/PGL#26]
Hallo, 
am having difficulties running the node2vec example on gpu 

the command python node2vec.py --use_cuda

it seems to work fine on cpu 

results in an error message 
Both GPU I use have 6GB. 
am I overseeing something ? 

0223 18:59:36.058634 11348 operator.cc:179] lookup_table raises an exception paddle::memory::allocation::BadAlloc, 

Out of memory error on GPU 0. Cannot allocate 6.933594GB memory on GPU 0, available memory is only 726.750000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please try one of the following suggestions:
   1) Decrease the batch size of your model.
   2) FLAGS_fraction_of_gpu_memory_to_use is 0.92 now, please set it to a higher value but less than 1.0.
      The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.

 at (/paddle/paddle/fluid/memory/detail/system_allocator.cc:151)

**Comment by WeiyueSu** [comment]
You may use smaller batch size by using `--batch_size 128`.

**Comment by almugabo** [comment]
thank you. Just tested it. It works. I am sorry I did not figure out that the default batch size is 1024. 
By the way, great framework.
