### ISSUE TITLE
1-Introduction运行问题

### ISSUE THREAD

**Issue by zeldarxf** [PaddlePaddle/PGL#27]
---------------------------------------------------------------------------EnforceNotMet                             Traceback (most recent call last)<ipython-input-17-70a3551d8554> in <module>
    111     feed_dict['node_label'] = label
    112 
--> 113     train_loss = exe.run(fluid.default_main_program(), feed=feed_dict, fetch_list=[loss], return_numpy=True)
    114     print('Epoch %d | Loss: %f'%(epoch, train_loss[0]))
    115 print('1')
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    649                 scope=scope,
    650                 return_numpy=return_numpy,
--> 651                 use_program_cache=use_program_cache)
    652         else:
    653             if fetch_list and program._is_data_parallel and program._program and (
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in _run(self, program, exe, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    747         self._feed_data(program, feed, feed_var_name, scope)
    748         if not use_program_cache:
--> 749             exe.run(program.desc, scope, 0, True, True, fetch_var_name)
    750         else:
    751             exe.run_cached_prepared_ctx(ctx, scope, False, False, False)
EnforceNotMet: Invoke operator sigmoid_cross_entropy_with_logits error.

**Comment by Liwb5** [comment]
Would you tell me your Paddle version and PGL version? I can run normally with Paddle==1.6 and PGL=1.0 .
