### ISSUE TITLE
node2vec代码的分布式cpu训练出来的embedding格式不对

### ISSUE THREAD

**Issue by tianrenheyi09** [PaddlePaddle/PGL#280]
我的输入数据
1 2
1 3
2 3
2 5
这种，建立图后用train_distributed_cpu.py训练，最后保存出来的格式
13738578341955826704    -1146019534     0       1       0.829162,0.498074,0.0460737,0.924469,0.572824,0.694283,0.945998,0.554342,0.260883,-0.0165946,0.606706,0.900473,0.937657,0.838645,-0.429151,-0.965522,0.749864,-0.873178,0.116757,-0.485003,-0.719742,0.497553,0.188762,0.260101,-0.252345,-0.538498,0.864228,-0.468023,-0.829096,0.0120238,-0.892463,-0.311652,0.818851,0.999642,0.675501,0.813562,-0.881616,-0.200093,0.454924,0.573881,-0.545228,0.77459,-0.481222,0.26993,0.555518,-0.65197,0.0104803,0.299641,0.620024,0.0291835,0.514216,0.553724,0.242989,0.803626,-0.184382,0.710944,0.486383,0.970202,0.0626079,0.331574,-0.271191,0.992374,-0.218454,0.541618,0.463211,-0.92811,-0.958322,-0.124145,-0.436136,-0.0887135,-0.632004,0.317223,-0.00482422,0.602483,0.418332,0.82509,-0.232131,-0.799192,-0.594804,0.169997,0.150191,0.860953,0.698477,0.919372,-0.435974,0.204695,-0.372071,0.0499396,-0.613687,0.221017,-0.441243,0.240976,0.960826,-0.952671,-0.777044,0.249277,0.83311,0.94917,0.413897,0.724666,-0.0259881,-0.959396,0.721776,-0.480212,-0.0668921,0.689045,0.191788,-0.994013,0.203871,-0.674879,0.211578,0.81094,-0.0548292,-0.915592,-0.397422,-0.99586,0.729191,0.0616742,0.24637,0.810132,-0.48238,0.190541,-0.932336,-0.243091,-0.223473,-0.996853,-0.208863,0.0260288,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0.999,0.0025,

"13738578341955826704    -1146019534     0       1    "这些是啥呢？
而且113738578341955826704 这个数字也不在我的文件中

**Comment by Yelrose** [comment]
谢谢反馈，我们优化一下输出文件。
目前保存出来的文件会带有一些meta信息（包括adam的一些动量参数），每一列的意义可以看*.meta文件。
