### ISSUE TITLE
The max edge ID should be  less than the number of nodes

### ISSUE THREAD

**Issue by cfangplus** [PaddlePaddle/PGL#289]
Hi,

I ran the python program of https://github.com/PaddlePaddle/PGL/tree/main/examples/kddcup2021/MAG240M/r_unimp/dataset/sage_institution_x.py and got error like this "The max edge ID should be  less than the number of nodes. But got max edge ID [122383104] >= num_nodes [25721]". So what does the maybe_num_nodes method of PGL graph.py do? As this is preprocessing part for this kdd cup mag240m dataset and what's the real problem?
Looking forward for your help.

**Comment by Yelrose** [comment]
@sys1874  please check this issue.

**Comment by sys1874** [comment]
Thanks for your report, the bug has been fixed.

**Comment by cfangplus** [comment]
another question, what's m2v and where is m2v_64.npy file. Is this source code same with your code for the KDD OGB competition ?
