### ISSUE TITLE
What's m2v_feat and where's m2v_64.npy file?

### ISSUE THREAD

**Issue by cfangplus** [PaddlePaddle/PGL#292]
欢迎您反馈PGL使用问题，非常感谢您对PGL的贡献！
在留下您的问题时，辛苦您同步提供如下信息：

#### 版本、环境信息
- PGL和PaddlePaddle版本号：latest
- 系统环境：Linux

#### 复现信息：
如下代码中，m2v_feat是什么，m2v_64.npy文件又在哪里？
https://github.com/PaddlePaddle/PGL/blob/main/examples/kddcup2021/MAG240M/r_unimp/r_unimp_multi_gpu_train.py

**Comment by Yelrose** [comment]
m2v_feat指的是我们在论文里面section 2.2的特征，是我们用MetaPath2vec训练得到的Embedding，其中m2v_64.npy是一个64维的network embedding特征。

我们论文和比赛是在50台MPI机器集群上跑的，@sys1874 同学会把对应的几种 npy文件放到google drive上  。

目前我们提供两个开源工具可以跑出相应的network embedding：

一个是动态图pgl 2.1版本的： https://github.com/PaddlePaddle/PGL/tree/main/examples/metapath2vec
和老版pgl 1.2 + paddle 1.8.5的版本： https://github.com/PaddlePaddle/PGL/tree/main/legacy/examples/distribute_metapath2vec

**Comment by cfangplus** [comment]
多谢，m2v_feature最后被添加到节点feature再进行Message Passing汇聚是吧，多谢。另外，我也发现了一个关于m2v_dim的硬编码问题，代码中写死成了128维，而配置文件中都是64维。我顺手提交了一个PR，https://github.com/PaddlePaddle/PGL/pull/294，请参考。

**Comment by Yelrose** [comment]
感谢贡献，代码已合入
