### ISSUE TITLE
reademe中一个日期写错了

### ISSUE THREAD

**Issue by medlen** [PaddlePaddle/PGL#293]
页面链接：https://github.com/PaddlePaddle/PGL/blob/main/README.zh.md

PGL v2.1 2020.02.02   <--------   根据上下文，这个日期应该是2021年

更易用了！正式发布PGL 2.1版本，正式支持PaddlePaddle 2.0
之前静态图版本（<2.0）的PGL放在“static_stable”分支

**Comment by Yelrose** [comment]
谢谢，已修复
