### ISSUE TITLE
ModuleNotFoundError: No module named 'pgl.graph_kernel'

### ISSUE THREAD

**Issue by medlen** [PaddlePaddle/PGL#296]
今天想针对PGL源码进行学习，于是直接下载了整个源码文件，然后运行了example中gcn里面的一个小例子，train.py 。 然后就报上面的错误了。 请问这个是什么原因？

**Comment by kirayummy** [comment]
请先使用pip install pgl进行安装 ：）

**Comment by Annihilation7** [comment]
> 请先使用pip install pgl进行安装 ：）

大佬我也遇到了这个问题，主要是根目录下也有一个pgl，导入pgl的时候没有从pip install里的pgl导入包，而是尝试从当前目录下导入导致报错 “ModuleNotFoundError: No module named 'pgl.graph_kernel'”  这个怎么解决呀

**Comment by medlen** [comment]
> 请先使用pip install pgl进行安装 ：）

我的目的是跑通整个源码文件，但是运行的过程中报了上面的错误，这应该是包里面有些内容不正确。例外我安装了pgl，但是仍然报了上面的错误。

**Comment by Yelrose** [comment]
不要在clone的根目录下执行 import pgl。直接cd example/gcn，然后python train.py。

**Comment by medlen** [comment]
> 不要在clone的根目录下执行 import pgl。直接cd example/gcn，然后python train.py。

在安装pgl之后，使用这个方法，确实可以正常运行了。

但是我的问题并不是利用已安装的pgl运行这个文件，而是用源码包中的pgl包去运行这个文件。

可以自己尝试一下复现这个问题：

step 1:  git clone https://github.com/PaddlePaddle/PGL.git
step 2: cd examples/gcn
step 3: python train.py 
result:
```
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    import pgl
ModuleNotFoundError: No module named 'pgl'
```

另一个尝试：
step 1:  git clone https://github.com/PaddlePaddle/PGL.git
step 2: cp -r pgl examples/gcn
step 3: cd examples/gcn
step 4: python train.py 
result:
```
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    import pgl
  File "/home/jinhl/PythonWorkspace/PGL/examples/gcn/pgl/__init__.py", line 20, in <module>
    from pgl import graph
  File "/home/jinhl/PythonWorkspace/PGL/examples/gcn/pgl/graph.py", line 25, in <module>
    import pgl.graph_kernel as graph_kernel
ModuleNotFoundError: No module named 'pgl.graph_kernel'
```

**Comment by Yelrose** [comment]
代码里面有需要编译连接的部分的部分

```
git clone https://github.com/PaddlePaddle/PGL.git
pip install -e .
cd examples/gcn
python train.py
```

**Comment by medlen** [comment]
问题解决了，感谢您的回复！
