### ISSUE TITLE
最新的版本里，metapath2vec 给了一个很好的例子在不同机器上起一个graph engine，但怎样让训练也跑在多台机器呢，求指点？

### ISSUE THREAD

**Issue by shuxinyin** [PaddlePaddle/PGL#297]
另外， graph engine模式下，切换成ps模式，会卡住，没有报错信息，这是什么原因呢？

**Comment by Liwb5** [comment]
1，目前我们在开发一套通用的分布式工具库用于支持游走类和图神经网络类的模型。最近我们会开源出来，可以关注一下我们的动态。
2，卡住是因为你开了dataloader的多进程么（num_workers）? 如果你开多进程的话，需要把graph client 放到__iter__函数中，即让每个进程都生成一个graph client。 如果不是这个原因的话，你可以贴一下更详细的代码，或者报错信息。

**Comment by shuxinyin** [comment]
是的，现在的graph client 就是放在TrainPairDataset中__iter__下，与给的example中 metapath2vec中位置及代码是一样,fleetrun collective 下没有问题，切换到ps会卡住，没有报错信息。😢😢

**Comment by shuxinyin** [comment]
接问一下，这个分布式工具库大概预计多久会发出来呢？？

**Comment by Yelrose** [comment]
> 是的，现在的graph client 就是放在TrainPairDataset中__iter__下，与给的example中 metapath2vec中位置及代码是一样,fleetrun collective 下没有问题，切换到ps会卡住，没有报错信息。😢😢

这个问题，ps多进程+图多进程采样，由于PS被fork会出点问题，我们还在修。暂时把num_workers设置为1，可以解决。

**Comment by shuxinyin** [comment]
> > 是的，现在的graph client 就是放在TrainPairDataset中__iter__下，与给的example中 metapath2vec中位置及代码是一样,fleetrun collective 下没有问题，切换到ps会卡住，没有报错信息。😢😢
> 
> 这个问题，ps多进程+图多进程采样，由于PS被fork会出点问题，我们还在修。暂时把num_workers设置为1，可以解决。

好的，明白了。

**Comment by Liwb5** [comment]
你好。我们的分布式工具库现在已经开源啦，欢迎使用，具体可以参考[这里](https://github.com/PaddlePaddle/PGL/tree/main/apps/Graph4Rec)
