### ISSUE TITLE
pgl.graph.Graph中的疑问

### ISSUE THREAD

**Issue by upenggod** [PaddlePaddle/PGL#298]
欢迎您反馈PGL使用问题，非常感谢您对PGL的贡献！
在留下您的问题时，辛苦您同步提供如下信息：

#### 版本、环境信息
- PGL和PaddlePaddle版本号：
PGL 2.1，PaddlePaddle2.1.1 -->

1.graph中的send_rev函数第946行调用send函数,传入message_func参数是{"msg": sf["h"]}吗？
2.sf对应src_feat={"h": feature}，df和ef就没有对应的数据？

**Comment by Yelrose** [comment]
这个send_recv函数是简单source发送，然后destination直接接收。如果需要操作 edge和 destination的特征，就分开用 send以及recv函数就好了。
