### ISSUE TITLE
使用PGL在CPU和GPU上的结果差很多

### ISSUE THREAD

**Issue by zhangpu1211** [PaddlePaddle/PGL#303]
PGL 2.1.5，PaddlePaddle2.1.0
代码地址：https://aistudio.baidu.com/aistudio/projectdetail/2246354
在ai studio上CPU结果在0.72左右，在GPU版本报错，在本地GPU上结果是0.2左右。
本地GPU结果：
在0.15-0.21之间波动
![l](https://user-images.githubusercontent.com/9513283/128144577-dbb40055-6269-4462-84cf-3b01dc86ed1c.png)
ai studio cpu 结果：
![c](https://user-images.githubusercontent.com/9513283/128144585-56c3c7f2-1259-4339-8096-777d1ec8d0bd.png)
ai studio gpu结果：
![g](https://user-images.githubusercontent.com/9513283/128144586-b99f4073-7795-4912-be44-32b190e1c01c.png)

**Comment by Yelrose** [comment]
好的，我看一下。

**Comment by Yelrose** [comment]
您试一下把PaddlePaddle的版本升级一下吧。
本地这边我使用PaddlePaddle版本 paddlepaddle-gpu==2.1.2 pgl==2.1.5 跑起来基本也正常。
Aistudio这边我帮你反馈一下，应该是平台的版本的问题。

**Comment by zhangpu1211** [comment]
> 您试一下把PaddlePaddle的版本升级一下吧。
> 本地这边我使用PaddlePaddle版本 paddlepaddle-gpu==2.1.2 pgl==2.1.5 跑起来基本也正常。
> Aistudio这边我帮你反馈一下，应该是平台的版本的问题。

貌似你们paddlepaddle-gpu==2.1.2只支持cuda10.2,我本地是11.2，按照官网安装的python -m pip install paddlepaddle-gpu==2.1.1.post112 -f https://paddlepaddle.org.cn/whl/mkl/stable.html，可以正常运行代码，但是准确率上不去，使用pip install -U paddlepaddle-gpu后，就报错
![QQ截图20210805153345](https://user-images.githubusercontent.com/9513283/128310364-a099b1f0-5daa-48d5-8d3d-307b642f8ea4.jpg)

**Comment by zhangpu1211** [comment]
> 您试一下把PaddlePaddle的版本升级一下吧。
> 本地这边我使用PaddlePaddle版本 paddlepaddle-gpu==2.1.2 pgl==2.1.5 跑起来基本也正常。
> Aistudio这边我帮你反馈一下，应该是平台的版本的问题。

安装了paddlepaddle 开发版以后正常了

**Comment by Yelrose** [comment]
> > 您试一下把PaddlePaddle的版本升级一下吧。
> > 本地这边我使用PaddlePaddle版本 paddlepaddle-gpu==2.1.2 pgl==2.1.5 跑起来基本也正常。
> > Aistudio这边我帮你反馈一下，应该是平台的版本的问题。
> 
> 安装了paddlepaddle 开发版以后正常了

**Comment by Yelrose** [comment]
> > 您试一下把PaddlePaddle的版本升级一下吧。
> > 本地这边我使用PaddlePaddle版本 paddlepaddle-gpu==2.1.2 pgl==2.1.5 跑起来基本也正常。
> > Aistudio这边我帮你反馈一下，应该是平台的版本的问题。
> 
> 安装了paddlepaddle 开发版以后正常了

谢谢反馈，具体我们也定位一下那个地方带来问题。
