### ISSUE TITLE
Some question about UniMP in IJCAI'21

### ISSUE THREAD

**Issue by S-rz** [PaddlePaddle/PGL#310]
I am a little confused about the label embedding, and my understand is UniMP initiates a label embedding with the size of (number_label, embedding_dimension), then uses it adds the nodes feature to be the input of GNN. In addition, this label embedding is also optimized in the training stage.
Do I understand correctly? Thanks.

**Comment by sys1874** [comment]
Yes, the label embedding is also learnable.

**Comment by S-rz** [comment]
> Yes, the label embedding is also learnable.

Thanks for your reply!
