### ISSUE TITLE
主页面图片无法加载

### ISSUE THREAD

**Issue by cfangplus** [PaddlePaddle/PGL#315]
#### 版本、环境信息
- PGL和PaddlePaddle版本号：Latest

- 系统环境：Linux

#### 复现信息：
https://pgl.readthedocs.io/en/latest/
主页面中，所述图片均无法加载，请问是对应png文件丢失了么？

**Comment by cfangplus** [comment]
It seems https://pgl.readthedocs.io/en/latest/introduction/introduction.html page is OK.
I guess the png file dir on https://pgl.readthedocs.io/en/latest/ html page line 208 is wrong.

**Comment by Liwb5** [comment]
Thank you for your feedback, we have fixed this problem.
