### ISSUE TITLE
demo跑不通

### ISSUE THREAD

**Issue by yifenzhong1920** [PaddlePaddle/PGL#327]
欢迎您反馈PGL使用问题，非常感谢您对PGL的贡献！
在留下您的问题时，辛苦您同步提供如下信息：

#### 版本、环境信息
- PGL和PaddlePaddle版本号：

- 系统环境：

linux
python 3.8
#### 复现信息：

Unsupervised GraphSAGE in PGL
python train.py --data_path ./sample.txt --num_nodes 2000 --phase train  demo例子跑不通，缺失包
AttributeError: module 'pgl' has no attribute 'graph_wrapper'

**Comment by WE1321254775** [comment]
> 这个示例是在静态图模式下运行的。pgl版本需要在1.2 下运行。目前最新的pg已经迁移到动态图模式下了，你也可以切换到main分支，这里的示例代码就可以在pgl2.0以上运行。

切换到main分支是什么意思啊

**Comment by Liwb5** [comment]
就是切换到git 的main 分支。 在main分支下面，examples目录下的模型代码在paddlepaddle==2.2 和pgl==2.2 下是可以跑通的。
