### ISSUE TITLE
AI Studio中的课程案例有错误

### ISSUE THREAD

**Issue by squllwu** [PaddlePaddle/PGL#328]
欢迎您反馈PGL使用问题，非常感谢您对PGL的贡献！
在留下您的问题时，辛苦您同步提供如下信息：

AI Studio中的课程案例有错误
https://aistudio.baidu.com/aistudio/projectdetail/2514298

#### 复现信息：
直接运行原始代码就出错了，修改 了版本后，又提示其他错误，希望协助解决
![image](https://user-images.githubusercontent.com/6859099/139520955-233b8272-b851-4da9-a18a-1c70bc58e4e7.png)

#### 版本、环境信息
- PGL和PaddlePaddle版本号：

- 系统环境：

**Comment by wawltor** [comment]
辛苦提供一下PaddlePaddle的版本？

**Comment by DesmonDay** [comment]
你好，使项目运行正确的最快方法，可以将项目代码中的`pip install pgl`修改为指定版本`pip install pgl==1.2.1`。主要原因是现在 PGL 已经升级为默认动态图，后续我们会讨论是否将课程代码统一升级为动态图，目前项目代码为静态图。
