### ISSUE TITLE
请教pgl安装问题

### ISSUE THREAD

**Issue by Jesey-git** [PaddlePaddle/PGL#35]
(paddle) C:\Users\l>pip install pgl
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement pgl (from versions: none)
ERROR: No matching distribution found for pgl

**Comment by Yelrose** [comment]
目前暂时还不支持Windows系统。

**Comment by Jesey-git** [comment]
好的，谢谢

**Comment by Qianli-Wu** [comment]
Hi, I failed to install pgl by "pip install -i https://mirror.baidu.com/pypi/simple pgl" on my M1 Mac.
I'm using miniforge3, python3.8, and I have installed paddlepaddle 2.3.2 and Cython 0.29.32.
The error message is:
ERROR: Could not find a version that satisfies the requirement pgl (from versions: none)
ERROR: No matching distribution found for pgl

**Comment by IvanaXu** [comment]
> Hi, I failed to install pgl by "pip install -i https://mirror.baidu.com/pypi/simple pgl" on my M1 Mac. I'm using miniforge3, python3.8, and I have installed paddlepaddle 2.3.2 and Cython 0.29.32. The error message is: ERROR: Could not find a version that satisfies the requirement pgl (from versions: none) ERROR: No matching distribution found for pgl

+1
