### ISSUE TITLE
module 'pgl' has no attribute 'sampling'

### ISSUE THREAD

**Issue by yaweisun** [PaddlePaddle/PGL#350]
#### 版本、环境信息
- PGL和PaddlePaddle版本号：
PGL 2.0.2，PaddlePaddle 2.1.5

- 系统环境：
AiStudio 高级版
Python 3.7

#### 复现信息：

首先：
`import pgl`
执行`help(pgl.sampling)`后，显示如下信息：

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> /tmp/ipykernel_7778/3153582152.py in <module>
> ----> 1 help(pgl.sampling)
> 
> AttributeError: module 'pgl' has no attribute 'sampling'

执行`help(pgl)`后，显示如下信息：

> Help on package pgl:
> 
> NAME
>     pgl - PGL
> 
> PACKAGE CONTENTS
>     dataset
>     graph
>     graph_kernel
>     heter_graph
>     math
>     message
>     nn (package)
>     sampling (package)
>     utils (package)
> 
> SUBMODULES
>     bigraph
>     op
> 
> VERSION
>     2.1.5
> 
> FILE
>     /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pgl/__init__.py

**Comment by Yelrose** [comment]
谢谢反馈。我们应该是在__init__.py里面缺了 import sampling了。可以先如下解决
```
from pgl import sampling
```

**Comment by yaweisun** [comment]
> 
可以了，谢谢
