### ISSUE TITLE
multiprocessing context has already been set

### ISSUE THREAD

**Issue by limengyuan988** [PaddlePaddle/PGL#355]
---------------------------------------------------------------------------RuntimeError                              Traceback (most recent call last)/tmp/ipykernel_161/639131080.py in <module>
----> 1 import pgl.utils.data
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pgl/utils/data/__init__.py in <module>
      1 #-*- coding: utf-8 -*-
      2 from .dataset import Dataset, StreamDataset, HadoopDataset
----> 3 from .dataloader import Dataloader
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pgl/utils/data/dataloader.py in <module>
     21 import paddle
     22 
---> 23 from pgl.utils import mp_reader
     24 from pgl.utils.data.dataset import Dataset, StreamDataset
     25 from pgl.utils.data.sampler import Sampler, StreamSampler
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pgl/utils/mp_reader.py in <module>
     17 log = logging.getLogger(__name__)
     18 import multiprocessing
---> 19 multiprocessing.set_start_method('fork')
     20 log.info("We set multiprocessing start method as 'fork' by default.")
     21 import copy
/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/context.py in set_start_method(self, method, force)
    240     def set_start_method(self, method, force=False):
    241         if self._actual_context is not None and not force:
--> 242             raise RuntimeError('context has already been set')
    243         if method is None and force:
    244             self._actual_context = None
RuntimeError: context has already been set

**Comment by DesmonDay** [comment]
你好，请问可以提供一个可复现的代码吗？我们这边排查一下~

**Comment by DesmonDay** [comment]
你好，可以提供一下具体的使用环境吗？包括使用系统、PGL 版本、Paddle版本等，我们这边排查一下~

**Comment by DesmonDay** [comment]
嗯嗯，我这边复现出问题了，会尽快解决的，谢谢！

**Comment by DesmonDay** [comment]
一个解决方式是回退一下 PGL 版本哈，可以暂时退回2.1版本。

**Comment by limengyuan988** [comment]
好的谢谢

**Comment by DesmonDay** [comment]
对了，可以顺便问问是哪个aistudio课程吗？





------------------ 原始邮件 ------------------
发件人: limengyuan988 ***@***.***&gt;
发送时间: 2021年12月16日 18:28
收件人: PaddlePaddle/PGL ***@***.***&gt;
抄送: Siming Dai ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [PaddlePaddle/PGL] import pgl.utils.data 报错 (Issue #355)





 
好的谢谢
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by limengyuan988** [comment]
图机器学习 我们学校的课程
