### ISSUE TITLE
请问一下单机单卡可以处理多大规模的数据？

### ISSUE THREAD

**Issue by Ramlinbird** [PaddlePaddle/PGL#365]
您好！请教一个计算问题，PGL搭建一个简单的节点分类网络，请问单机单卡可以处理多少节点、多少边的数据呢？
我有一个千万节点、数亿条边的user-item网络（原始数据gz压缩5GB），单机单卡能处理吗？应该一次性加载不了这么大的数据集？请问有没有相关操作指南，谢谢！

**Comment by Ramlinbird** [comment]
@Liwb5 hello，大佬，刚才感谢答复Import的问题。这个实践上的问题方便给些指南吗？谢谢~😊

**Comment by Liwb5** [comment]
可以根据以下公式大概估计一下内存： 边的数量 * int64 + 节点量 * 特征量 * float

**Comment by Ramlinbird** [comment]
> 可以根据以下公式大概估计一下内存： 边的数量 * int64 + 节点量 * 特征量 * float

好哒，感谢感谢~
