### ISSUE TITLE
ImportError: cannot import name 'heter_graph_wrapper'

### ISSUE THREAD

**Issue by Ramlinbird** [PaddlePaddle/PGL#366]
#### 版本、环境信息
- PGL和PaddlePaddle版本号：
paddlepaddle-gpu                  2.1.2
pgl                               2.2.2
- 系统环境：
ubuntu, Python 3.6.9
#### 复现信息：
![image](https://user-images.githubusercontent.com/11084132/150312317-d46d5f98-6480-4baf-80dd-d276fe9ea1b9.png)

**Comment by Liwb5** [comment]
heter_graph_wrapper 是静态图版本的接口。 如需使用，需要将paddlepaddle-gpu的版本设置为1.8.5， pgl的版本为1.2

**Comment by Ramlinbird** [comment]
> heter_graph_wrapper 是静态图版本的接口。 如需使用，需要将paddlepaddle-gpu的版本设置为1.8.5， pgl的版本为1.2

感谢如此迅捷的答复，我其实是想搭建异构图网络，请问下有没有适合该版本的代码教程呢？

**Comment by Liwb5** [comment]
pgl2.0以上的版本可以参考[这里](https://github.com/PaddlePaddle/PGL/blob/main/tutorials/working_with_hetergraph.ipynb)

**Comment by Ramlinbird** [comment]
> pgl2.0以上的版本可以参考[这里](https://github.com/PaddlePaddle/PGL/blob/main/tutorials/working_with_hetergraph.ipynb)

GET! Thanks a lot!👍
