### ISSUE TITLE
请问Graph4Rec支持的算法中，如何添加节点特征信息？

### ISSUE THREAD

**Issue by zbmain** [PaddlePaddle/PGL#373]
请问Graph4Rec支持的算法中，如何添加节点特征信息，例如uniMP模型中的nfeat.npy

configs - .yaml有配置{**nfeat_info: null**}，请问{**nfeat_info**}该如何配置？

**Comment by Liwb5** [comment]
目前只支持ID 特征，具体的配置后续会提供一个示例出来。

**Comment by Liwb5** [comment]
示例已提供， 可以参考这个PR [#374](https://github.com/PaddlePaddle/PGL/pull/374/files)

**Comment by zbmain** [comment]
收到，感谢回复。可否告知一下ID特征如何配置吗？相关文章或论文地址也好。谢谢

**Comment by Liwb5** [comment]
参考这个示例 [#374](https://github.com/PaddlePaddle/PGL/pull/374/files)，里面有详细的配置。
