### ISSUE TITLE
请问PGL未来是否会支撑便捷的时序特征输入

### ISSUE THREAD

**Issue by fly2008begin** [PaddlePaddle/PGL#377]
请问这个项目未来会有支撑为 Graph 叠加时序特征的计划吗，如STGAT，STGCN等可以导入时序特征的，通过阅读现有的示例我感觉大多都是每一个节点是样本，而对于如骨架识别，交通路网预测等均是需要对同一个Graph 引入时间帧的概念的。

**Comment by Yelrose** [comment]
这块PGL上面的demo我们也在开发中。
纯时空的你可以先看看 PaddleSpatial工具库，里面也有用PGL实现 时空图卷积网络. https://github.com/PaddlePaddle/PaddleSpatial/blob/f4ec7a8affc7627919cde7ccf010f2db1dbd447e/paddlespatial/networks/sagnn.py
