### ISSUE TITLE
AttributeError: module 'pgl' has no attribute 'graph_wrapper'

### ISSUE THREAD

**Issue by Taoboan1999** [PaddlePaddle/PGL#405]
我在复现examples里的stgcn 在创建一个图的时候出了这样一个bug：
AttributeError: module 'pgl' has no attribute 'graph_wrapper'

    with fluid.program_guard(train_program, startup_program):
        gw = pgl.graph_wrapper.GraphWrapper(
            name="gw",
            node_feat=[('norm', [None, 1], "float32")],
            edge_feat=[('weights', [None, 1], "float32")])

        model = STGCNModel(args, gw)
        train_loss, y_pred = model.forward()

请问如何解决呢

**Comment by kirayummy** [comment]
PGL在version >= 2.0的时候进行了重构（主要适配了Paddle的动态图），变动较大。这个graph_wrapper是1.x版本时的类，可使用1.x版本PGL进行建模，如
pip install pgl==1.2.1
