### ISSUE TITLE
请问静态图中如何使用PGL，在TIPC中运行to_static时遇到了几个问题？

### ISSUE THREAD

**Issue by BamLubi** [PaddlePaddle/PGL#407]
背景：百度论文复现赛中一篇模型需要PGL。在使用TIPC时，需要转换成静态图，出现了几个问题。（动态图中没有问题）
- 问题1: `pgl.Graph.disjoint`方法，[报错信息图片](https://picgo-1256052225.cos.ap-guangzhou.myqcloud.com/batch.png)
 ```
使用：
graphs = pgl.Graph.batch(graphs).tensor()

报错：
/site-packages/pgl/graph.py line 1208
    if len(edges) > 0:
TypeError: object of type 'Variable' has no len()
```
- 问题2: `pgl.Graph.send`方法，[报错信息图片](https://picgo-1256052225.cos.ap-guangzhou.myqcloud.com/send.png)
 ```
使用：
msg = graph.send(self._send_func, ...)

报错：
/site-packages/pgl/graph.py line 264
    num_nodes = self.num_nodes.numpy()
'numpy' only can be called by 'paddle.Tensor' in dynamic graph mode
```

**Comment by kirayummy** [comment]
麻烦提供一下PGL的版本

**Comment by BamLubi** [comment]
pgl==2.2.0
paddlepaddle==2.2.2

**Comment by Yelrose** [comment]
静态图做 子图Batch可以参考这里。

数据流dataset参照下面代码: 数据流全程使用numpy操作，在数据流dataset里面合并子图，然后通过feed_dict传到静态计算图。您的用法上面静态图是不支持 .tensor的用法的。
https://github.com/PaddlePaddle/PGL/blob/main/apps/Graph4Rec/env_run/src/datasets/dataset.py#L533

组网部分的修改：增加 static.data来存图的edges nodes feature，然后像下面L255一样，在forward阶段把图组合。
https://github.com/PaddlePaddle/PGL/blob/main/apps/Graph4Rec/env_run/src/models/model.py#L255

**Comment by BamLubi** [comment]
感谢您的建议，请问消息传递阶段，`graph.send`是否也支持静态图调用呢
