### ISSUE TITLE
ImportError: cannot import name 'data_loader' from 'pgl' 

### ISSUE THREAD

**Issue by Adele0108** [PaddlePaddle/PGL#414]

**Comment by kirayummy** [comment]
Please provide the version of pgl and paddlepaddle, thx!

**Comment by Adele0108** [comment]
谢谢！这个问题已经解决了，但是在运行kddcup2022/wpf_baseline的main.py后，再运行predict.py时，显示如下：
RuntimeWarning: Mean of empty slice.谢谢！这个问题已经解决了，但是在运行kddcup2022/wpf_baseline的main.py后，再运行predict.py时，显示如下：
RuntimeWarning: Mean of empty slice.
  avg_rmse = np.array(rmses).mean()

 --- Final MAE: nan, RMSE: nan ---
--- Final Score --- 
	nan
并且没有prediction data into  ./predict_data/test_x and ./predict_data/test_y

**Comment by Adele0108** [comment]
谢谢！这个问题已经解决了，但是在运行kddcup2022/wpf_baseline的main.py后，再运行predict.py时，显示如下：
RuntimeWarning: Mean of empty slice.
  avg_rmse = np.array(rmses).mean()

 --- Final MAE: nan, RMSE: nan ---
--- Final Score --- 
	nan
并且没有prediction data into  ./predict_data/test_x and ./predict_data/test_y

**Comment by Adele0108** [comment]
谢谢！这个问题已经解决了，但是在运行kddcup2022/wpf_baseline的main.py后，再运行predict.py时，显示如下：
RuntimeWarning: Mean of empty slice.
avg_rmse = np.array(rmses).mean()

--- Final MAE: nan, RMSE: nan ---
--- Final Score ---
nan
并且没有prediction data into ./predict_data/test_x and ./predict_data/test_y

**Comment by Yelrose** [comment]
可以参考里面的目录构造，把测试数据摆到这个predict_data/test_x, predict_data/test_y就可以了

https://github.com/PaddlePaddle/PaddleSpatial/tree/main/apps/wpf_baseline_gru/kddcup22-sdwpf-evaluation/data/sdwpf_baidukddcup2022_test_toy/test_x

**Comment by Henrry-2000** [comment]
我遇到了同样的问题，请问则呢1？

**Comment by Liwb5** [comment]
你安装的pgl==2.2.3（动态图版本）， 但是你clone下来的代码应该是1.2版本（静态图版本），需要重新更新代码。

**Comment by Henrry-2000** [comment]
有什么办法能pip install pgl==1.2 呢？这个版本在仓库里已经找不到了。。



***@***.***
 
From: Webbley
Date: 2022-07-15 15:14
To: PaddlePaddle/PGL
CC: Henrry-2000; Comment
Subject: Re: [PaddlePaddle/PGL] ImportError: cannot import name 'data_loader' from 'pgl' (Issue #414)
你安装的pgl==2.2.3（动态图版本）， 但是你clone下来的代码应该是1.2版本（静态图版本），需要重新更新代码。
―

**Comment by UncleLLD** [comment]
paddlepaddle 版本与pgl版本 要一致， 如果paddlepaddle==1.8.5,  pgl==1.2.1;
