### ISSUE TITLE
官方metapath2vec分布式demo infer报错，请教一下大佬

### ISSUE THREAD

**Issue by JintaiYang** [PaddlePaddle/PGL#415]
https://github.com/PaddlePaddle/PGL/tree/main/apps/Graph4Rec
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/18062960/173236893-0dc6423d-50eb-4e5c-a3f1-f845a246429c.png">

完全按照官方这个demo跑到模型，
单GPU train, infer  这个没有问题
单机版的分布式 CPU training 没有问题， 分布式CPU训练完之后，分布式infer一直报错。

<img width="1682" alt="image" src="https://user-images.githubusercontent.com/18062960/173236769-09345ffe-5f72-43a1-9ff5-9f3b5e24b99e.png">

ckpt_custom 这个目录下是有模型数据的。 请教一下大佬帮忙看一下什么问题

额外一个问题，对于metapath2vec，node没有特征的情况下，ckpt_custom的向量是不是和最终embedding出来的向量一样的？  一位模型就一个隐藏层。

**Comment by Liwb5** [comment]
可能paddle分布式有bug，你可以先回退到paddle=2.2.2， pgl=2.1.5 的版本试一下。

是的。对于metapath2vec， 在没有节点特征的情况下，ckpt_custom的向量和最终embedding出来的向量是一样的。
