### ISSUE TITLE
如果我想在最新版上使用GES等以前版本里面的example中的model，要如何做？

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PGL#421]
legacy里面有不少函数在新版里都改了
另外ges的例子使用的是[BlogCatalog]数据集，我看了下这个数据集，似乎只有节点和边的信息以及他们分类的信息，GES是能建模其他辅助信息的，那比如我的节点有10维特征，边也有5维特征，如何构造模型需要的数据集？

**Comment by DesmonDay** [comment]
在构造Graph结构的时候，可以选择把节点特征和边特征放到图中就可以了。
![截屏2022-06-24 上午11 17 06](https://user-images.githubusercontent.com/20554008/175455248-1c4e76a4-9683-464b-bc28-3ef4588577a0.png)
也可以选择额外拎出来，需要计算的时候再取对应的特征。
