### ISSUE TITLE
请问有什么办法将例子example 的 PGL1.0代码能转成PGL2.0的？

### ISSUE THREAD

**Issue by yangnianen** [PaddlePaddle/PGL#423]
example的 API差距太大了，总不能下载1.0又下载2.0来跑把，很难学习，也太难用了。我估计大家都有和我一样的想法，这个太重要了。

**Comment by yangnianen** [comment]
2.0 一个异构体的案例实践都没有？

**Comment by Yelrose** [comment]
🙏感谢您的反馈。抱歉，因为1.0跟2.0具体的使用上有比较大的版本更替。
有些API为了性能以及方便进行了重构，特别是之前Paddle 1.X时代是静态图的，Paddle 2.0是动态图的。

1.0部分基础代码基本都迁移过来了，还有些代码暂时还没有挪过来，后面我们会加强这方面建设。

您说的异构图的案例，可以参考这里。
RGCN: https://github.com/PaddlePaddle/PGL/blob/main/examples/rgcn/train.py
KDDCup 2021异构图数据集MAG240M: https://github.com/PaddlePaddle/PGL/tree/main/ogb_examples/lsc/MAG240M

还有由于deepwalk、graphsage，同构图、异构图，这些组合特别的多，我们在2.0也做了一个工具包。
基本上可以配置化，把您说的异构图的东西都跑上。

https://github.com/PaddlePaddle/PGL/tree/main/apps/Graph4Rec

**Comment by yangnianen** [comment]
谢谢了，因为听了你们的所有课，实践时候差距甚远。PGL2.0确实很强大，也很易用，我相信大部分都像我们这种硕士博士一样，搞研究的或者工业开发的，都难以手动写，需要案例辅助才能真正落地点成果。
