### ISSUE TITLE
真实应用场景实践问题

### ISSUE THREAD

**Issue by yangnianen** [PaddlePaddle/PGL#427]
请教一下。
案例背景：P2P 中寻找欺诈黑户，黑户1 ，正常客户 0
用异构图RGCN
节点： 信用卡，用户，IP，设备
关系：用户对信用卡，用户对ID，用户对设备，用户对用户
特征：用户：金额， 其他节点没有特征

因为我是要预测客户，所以其他节点是没有标签，也没有特征，我应该用nan还是0代替其他节点的特征和标签？

**Comment by yangnianen** [comment]
信用卡，IP，设备 只有和用户的关系特征，没有节点内的特征。因为官方文档上写着，只有关系特征，也要把这个加上。
![image](https://user-images.githubusercontent.com/17618881/176170609-428a9b63-2b6a-47e1-81e7-ebe0d9f1bb2c.png)

**Comment by yangnianen** [comment]
而用户有好几个节点特征，如果我不把其他节点特征设置为空特征和任意标签，拼成和总节点一样的条数的话，就会报错说越界。

**Comment by Liwb5** [comment]
你的节点特征是浮点数吗？还是离散特征？如果是离散特征的话，建议使用https://github.com/PaddlePaddle/PGL/tree/main/apps/Graph4Rec 这个代码库来训练，得到每个节点的embedding，然后再写一个分类器（例如：MLP模型）来给每个节点做分类任务。

**Comment by yangnianen** [comment]
节点特征有浮点型的，因为有金额这个字段。
