### ISSUE TITLE
关于Graph4Rec的数据问题

### ISSUE THREAD

**Issue by yangnianen** [PaddlePaddle/PGL#438]
<img width="276" alt="7a326616339ba626ef7d0497396f08a" src="https://user-images.githubusercontent.com/17618881/180194037-6307ad42-c7af-4ebf-b760-d848acd35bdc.png">
<img width="244" alt="8334b3323f25a116bb6e0a116d0e61c" src="https://user-images.githubusercontent.com/17618881/180194056-37cc8f3a-3d08-469b-9b62-073cdaa486c4.png">

这个应该是节点的特征，但是为什么不是一条向量，而是这种结构有点看不懂？  s 1:583,2:697 这样表示的什么意思？

**Comment by zouhan6806504** [comment]
> <img alt="7a326616339ba626ef7d0497396f08a" width="276" src="https://user-images.githubusercontent.com/17618881/180194037-6307ad42-c7af-4ebf-b760-d848acd35bdc.png">
> 
> <img alt="8334b3323f25a116bb6e0a116d0e61c" width="244" src="https://user-images.githubusercontent.com/17618881/180194056-37cc8f3a-3d08-469b-9b62-073cdaa486c4.png">
> 
> 这个应该是节点的特征，但是为什么不是一条向量，而是这种结构有点看不懂？ s 1:583,2:697 这样表示的什么意思？

目前只支持id特征，向量的不支持，话说你能运行成功graph4rec吗，我在aistudio上跑着会报错

**Comment by yangnianen** [comment]
@zouhan6806504 我是在自己服务器上跑的，可以跑通。这么坑，s 1:583,2:697 表示第一个特征和第二个特征的意思？ 583和697表示特征具体的值嘛

**Comment by Liwb5** [comment]
这个问题可以看这个issue： https://github.com/PaddlePaddle/PGL/issues/434

**Comment by Liwb5** [comment]
举个例子： 比如节点是一篇文章，这个文章有这样的特征： 标题 和 类别（娱乐，军事，政治），那么我们就可以用1，表示标题属性，用2表示类别属性。 我们称之为slot，所以就有两个slot，1和2， 然后697是值，表示这个是娱乐新闻。 这样的特征其实也是离散特征，所以在代码里面，我们也是会给他们创建embedding的。

**Comment by zzw1123** [comment]
> 举个例子： 比如节点是一篇文章，这个文章有这样的特征： 标题 和 类别（娱乐，军事，政治），那么我们就可以用1，表示标题属性，用2表示类别属性。 我们称之为slot，所以就有两个slot，1和2， 然后697是值，表示这个是娱乐新闻。 这样的特征其实也是离散特征，所以在代码里面，我们也是会给他们创建embedding的。

所以如果一共有N个类别的话，s 1:583,2:697这个2后边的值的范围就是从1~N（或者从0~N-1）？
