### ISSUE TITLE
没有报错，数据集格式相同，但是无法正常读入。

### ISSUE THREAD

**Issue by xinDongY** [PaddlePaddle/PGL#446]
ps：
26670818	情定河州
25815002	我不是李小龙
26392287	曼哈顿中国女孩
26695995	绿毛水怪
26392292	为了祖国
6389523	天地无用
26266621	看不见的脸
26647079	你无法抵达的时间
26277337	黑夜之神

报错：
[INFO] 2022-08-02 21:06:25,702 [dist_graph.py:  201]:   load edges of type user2movie from ./graph4rec_douban_small/rec_data/user2movie.txt
I0802 21:06:25.702848 13589 graph_py_service.cc:245] loadding data with type user2movie from ./graph4rec_douban_small/rec_data/user2movie.txt
I0802 21:06:25.704360 14037 common_graph_table.cc:284] 0/0 edges are loaded successfully in ./graph4rec_douban_small/rec_data/user2movie.txt
I0802 21:06:25.704452 13938 common_graph_table.cc:284] 0/0 edges are loaded successfully in ./graph4rec_douban_small/rec_data/user2movie.txt
I0802 21:06:25.704563 13891 common_graph_table.cc:284] 0/0 edges are loaded successfully in ./graph4rec_douban_small/rec_data/user2movie.txt
I0802 21:06:25.704581 13954 common_graph_table.cc:284] 0/0 edges are loaded successfully in ./graph4rec_douban_small/rec_data/user2movie.txt
I0802 21:06:25.705765 13589 graph_py_service.cc:245] loadding data with type movie2user from ./graph4rec_douban_small/rec_data/user2movie.txt
I0802 21:06:25.705967 14038 common_graph_table.cc:284] 0/0 edges are loaded successfully in ./graph4rec_douban_small/rec_data/user2movie.txt
I0802 21:06:25.706014 13987 common_graph_table.cc:284] 0/0 edges are loaded successfully in ./graph4rec_douban_small/rec_data/user2movie.txt
I0802 21:06:25.706033 13873 common_graph_table.cc:284] 0/0 edges are loaded successfully in ./graph4rec_douban_small/rec_data/user2movie.txt
I0802 21:06:25.706043 13924 common_graph_table.cc:284] 0/0 edges are loaded successfully in ./graph4rec_douban_small/rec_data/user2movie.txt
[INFO] 2022-08-02 21:06:25,706 [dist_graph.py:  211]:   load nodes of type user from ./graph4rec_douban_small/rec_data/node_types.txt
I0802 21:06:25.706733 14034 common_graph_table.cc:236] 0/0 nodes in type user are loaded successfully in ./graph4rec_douban_small/rec_data/node_types.txt
I0802 21:06:25.706792 13885 common_graph_table.cc:236] 0/0 nodes in type user are loaded successfully in ./graph4rec_douban_small/rec_data/node_types.txt
I0802 21:06:25.706809 13895 common_graph_table.cc:236] 0/0 nodes in type user are loaded successfully in ./graph4rec_douban_small/rec_data/node_types.txt
I0802 21:06:25.706885 13975 common_graph_table.cc:236] 0/0 nodes in type user are loaded successfully in ./graph4rec_douban_small/rec_data/node_types.txt
[INFO] 2022-08-02 21:06:25,707 [dist_graph.py:  211]:   load nodes of type movie from ./graph4rec_douban_small/rec_data/node_types.txt
I0802 21:06:25.707293 14037 common_graph_table.cc:236] 0/0 nodes in type movie are loaded successfully in ./graph4rec_douban_small/rec_data/node_types.txt
I0802 21:06:25.707330 13973 common_graph_table.cc:236] 0/0 nodes in type movie are loaded successfully in ./graph4rec_douban_small/rec_data/node_types.txt
I0802 21:06:25.707336 13891 common_graph_table.cc:236] 0/0 nodes in type movie are loaded successfully in ./graph4rec_douban_small/rec_data/node_types.txt
I0802 21:06:25.707432 13878 common_graph_table.cc:236] 0/0 nodes in type movie are loaded successfully in ./graph4rec_douban_small/rec_data/node_types.txt

-----------------------

另外，想知道如何查看图引擎所构建起来的图。感谢解答

**Comment by Liwb5** [comment]
一般是数据路径跟配置文件的路径配置匹配不上。请仔细查看配置。
