### ISSUE TITLE
training and inference time

### ISSUE THREAD

**Issue by aries-M** [PaddlePaddle/PGL#450]
may I ask the training and inference time for the OGB LCS challenge?

**Comment by DesmonDay** [comment]
For MAG240M, we train a R-UniMP for roughly 48 mins for an epoch, and 5 mins to infer.  Here We use part of the validation set for training, so the actual validation set size becomes smaller.
For WikiKG90M, in my memory it takes 5 hours to train a TransE model.

**Comment by aries-M** [comment]
Thank you for the reply! What about the inference time of a single model and the ensemble model for WikiKG90M?

**Comment by aries-M** [comment]
> For MAG240M, we train a R-UniMP for roughly 48 mins for an epoch, and 5 mins to infer. Here We use part of the validation set for training, so the actual validation set size becomes smaller. For WikiKG90M, in my memory it takes 5 hours to train a TransE model.

Could u please provide the information of the machine used?

**Comment by DesmonDay** [comment]
We use 4-cards V100 machine. And for Wikikg90m, the actual validation set size is also smaller, so the inferecence time of a single model is roughly 10 minutes. If you use the original validation set, it will take much longer time.

**Comment by aries-M** [comment]
Thank you!
