### ISSUE TITLE
要使用example里面的r_unimp，要如何准备数据？

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PGL#454]
meta2vec的模型已经训练好了，可以获得节点特征，要如何存放边、节点、关系这些属性，才能运行example里面的r_unimp？不用那么fold融合，只需要训练单模型

**Comment by Yelrose** [comment]
https://github.com/PaddlePaddle/PGL/blob/main/examples/kddcup2021/MAG240M/r_unimp/dataset/data_generator_r_unimp_sample.py#L273

如果你只要跑单模型，应该要把这块改回官方的split就好了
