### ISSUE TITLE
metapath2vec for mag240m

### ISSUE THREAD

**Issue by hwangyeong** [PaddlePaddle/PGL#458]
您好，请问在mag240m上用metapath2vec得到的节点表示文件现在是可获得的嘛？

https://github.com/PaddlePaddle/PGL/issues/292#issuecomment-881803777

**Comment by Yelrose** [comment]
我们已经将MAG240M 训练好的 m2v_embedding 提供了云盘下载的地址。具体看下面链接里面，m2v embedding部分
[https://github.com/PaddlePaddle/PGL/tree/main/examples/kddcup2021/MAG240M/r_unimp](https://github.com/PaddlePaddle/PGL/issues/url)
