### ISSUE TITLE
【Single GPU training and inference】里的例子只能在物理机上执行吗？

### ISSUE THREAD

**Issue by Ramlinbird** [PaddlePaddle/PGL#481]
你好，请问下【Single GPU training and inference】的例子，在docker容器内可以执行的吗？ip_list.txt总是报连接失败错误，应该如何解决？谢谢~

**Comment by Ramlinbird** [comment]
> docker run -it --rm --network host --ipc=host
> 
> 可能需要加这两个参数吧

没有宿主机权限，只能在ubuntun虚拟机内执行命令😂还有解法吗

**Comment by Liwb5** [comment]
请参考toy_data 里面的ip_list.txt。 我这边都是这样填就好了的。

**Comment by Ramlinbird** [comment]
OK了，谢谢~
