### ISSUE TITLE
Loss下降很快，还有多少学习空间？

### ISSUE THREAD

**Issue by Ramlinbird** [PaddlePaddle/PGL#482]
请教一下，我的二部图有2万节点左右（u和i分别1万），关系对230万对。训练参数
```
walk_len: 24
win_size: 3
neg_num: 10
walk_times: 10

epochs: 50
num_workers: 1
lr: 0.005
lazy_mode: True
batch_node_size: 500 
batch_pair_size: 1200
```
loss曲线很快就平了，请教下如何判断是否学习已经充分呢？试了不同的学习率，好像影响不大，都是大概2个epoch就平缓了。
![image](https://user-images.githubusercontent.com/11084132/197184993-aeeee5dd-9a65-4f30-a797-bada5894be3d.png)

**Comment by Liwb5** [comment]
一般直接看下游任务的评估指标。

**Comment by Ramlinbird** [comment]
好的，感谢回复~
