### ISSUE TITLE
SegmentPool 利用 CPU 并行

### ISSUE THREAD

**Issue by clearhanhui** [PaddlePaddle/PGL#484]
在最近阅读 PGL 和 paddlepaddle 代码的过程中，发现 PGL 中常用的一个 api [segment_pool](https://github.com/PaddlePaddle/PGL/blob/main/pgl/math.py#L36) 似乎在对应的 paddlepaddle 的 [cpp代码](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/funcs/segment_pooling.cc#L41) 中只有一个单线程实现，不能充分利用多核CPU的计算能力。不知道这样设计的出发点是什么呢，以后有改进的计划吗？

**Comment by DesmonDay** [comment]
通常我们更多的是利用GPU来计算，所以对于CPU这块的计算优化相对会少一些。如果你有相应的需求，我们这边也可以进行优化。
