### ISSUE TITLE
GraphSAGE怎么修改聚合函数类型，有类似超参数吗

### ISSUE THREAD

**Issue by dingidng** [PaddlePaddle/PGL#497]
看官网目前demo是mean的聚合函数，还有提供其他的类型吗
graphsage_mean”, “graphsage_maxpool”, “graphsage_meanpool” 和 “graphsage_lstm”

**Comment by Yelrose** [comment]
谢谢，提醒我们也发现了GraphSAGE，放出来的版本，没把聚合函数的flag提供出来。目前graphsage可以提供其他类型的，但是可能要手动改这里的聚合函数 https://github.com/PaddlePaddle/PGL/blob/main/examples/graphsage/model.py#L39

我们最近也打算把 GraphSAGE模型提供些更方便的API
