### ISSUE TITLE
PGL2.x版本erniesage有详细文档吗？看了example下没有，只有old版本有1.7框架支持的erniesage？

### ISSUE THREAD

**Issue by dingidng** [PaddlePaddle/PGL#499]
PGL2.x版本erniesage有详细文档吗？看了example下没有，只有old版本有1.7框架支持的erniesage？

**Comment by Yelrose** [comment]
2.X版本的，可以直接用PaddleNLP这边的迁移

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_graph/erniesage
