### ISSUE TITLE
您好UniMP算法有paddle2.x版本的支持嘛，我看安装依赖paddle1.8.3而且还有torch安装，在aistudio是禁用的。

### ISSUE THREAD

**Issue by dingidng** [PaddlePaddle/PGL#500]
您好UniMP算法有paddle2.x版本的支持嘛，我看安装依赖paddle1.8.3而且还有torch安装，在aistudio是禁用的。

`    git clone https://github.com/PaddlePaddle/PGL.git
    cd PGL
    pip install -e 
    pip install -r requirements.txt
    `
paddlepaddle_gpu==1.8.3.post107
torch==1.5.1
tqdm==4.31.1
six==1.12.0
numpy==1.21.0
ogb==1.2.1

**Comment by DesmonDay** [comment]
可以看我们最近放出来的[NeurIPS2022-OGB-Challenge/MAG240M](https://github.com/PaddlePaddle/PGL/tree/main/examples/NeurIPS2022-OGB-Challenge/MAG240M)例子，里面用的是R-UniMP算法。可以自行参考一下。
