### ISSUE TITLE
PGL Box 报错

### ISSUE THREAD

**Issue by xbinglzh** [PaddlePaddle/PGL#517]
![图片](https://user-images.githubusercontent.com/1407233/208008510-d0708176-17b1-442e-bf75-b71a363e55a8.png)
mag240m 的数据很大 24g，运行到 STAGE [GPU Load] end load edge into GPU, type[inst2author]  后就直接退出了，也没有报错，开了debug 也看不到报错日志，我已经拉了最新的main 分支代码， 是代码没推完整吗， 还是数据量太大了 ，我显卡跑不了，我机器是2张卡， 没看到哪里配置说明是 多卡训练，不支持多机多卡么，目前看只是docker 里单机运行。后面是否能提供在k8s 上可以跑的 yarm 环境，支持多机多卡。我没有百度一体机 没有1机8卡的设备。需要多机多卡运行。 mag240m数据量太大了， 能否提供小数据集快速验证的。可以提供一份 没有 sharding_tool 之前的 ，测试下 sharding 到运行的整体流程。谢谢。

**Comment by Liwb5** [comment]
mag240m 数据量相对较大，2卡确实有可能跑不动。 这里有一份比较小的数据集UB（User Behavior），大概有500万节点，1亿的边。可以试一下UB数据集。

原始数据地址：https://baidu-pgl.gz.bcebos.com/pglbox/data/UB/raw_UB.tar.gz
已经sharding好的数据地址：https://baidu-pgl.gz.bcebos.com/pglbox/data/UB/preprocessed_UB.tar.gz
配置文件地址：https://baidu-pgl.gz.bcebos.com/pglbox/data/UB/UB_metapath2vec.yaml

目前我们只能支持单机多卡（v100 或 a100 机器），多机的还在研发中。

**Comment by xbinglzh** [comment]
![图片](https://user-images.githubusercontent.com/1407233/208030717-2f1788f3-8904-4937-80d9-da970dec7226.png)
试了小数据集 UB 还是报错， 是显卡不支持吗

F1216 05:44:12.948030   795 graph_gpu_ps_table_inl.cu:951] Check failed: e == cudaSuccess Cuda failure /root/paddlejob/paddle.jxw/Paddle/paddle/fluid/framework/fleet/heter_ps/graph_gpu_ps_table_inl.cu:951 invalid argument
*** Check failure stack trace: ***
F1216 05:44:12.949337   796 graph_gpu_ps_table_inl.cu:951] Check failed: e == cudaSuccess Cuda failure /root/paddlejob/paddle.jxw/Paddle/paddle/fluid/framework/fleet/heter_ps/graph_gpu_ps_table_inl.cu:951 invalid argument
*** Check failure stack trace: ***
    @     0x7f864629f15d  google::LogMessage::Fail()
    @     0x7f864629f15d  google::LogMessage::Fail()
    @     0x7f86462a140d  google::LogMessage::SendToLog()
    @     0x7f86462a140d  google::LogMessage::SendToLog()
    @     0x7f864629ec4d  google::LogMessage::Flush()
    @     0x7f864629ec4d  google::LogMessage::Flush()
    @     0x7f86462a1f09  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f864988e9ea  paddle::framework::GpuPsGraphTable::graph_neighbor_sample_v2()
    @     0x7f86462a1f09  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f8649891829  paddle::framework::GpuPsGraphTable::graph_neighbor_sample_v3()
    @     0x7f864988e9ea  paddle::framework::GpuPsGraphTable::graph_neighbor_sample_v2()
    @     0x7f864654b147  paddle::framework::GraphGpuWrapper::graph_neighbor_sample_v3()
    @     0x7f8646385738  paddle::framework::GraphDataGenerator::FillWalkBuf()
    @     0x7f8649891829  paddle::framework::GpuPsGraphTable::graph_neighbor_sample_v3()
    @     0x7f8646386297  paddle::framework::GraphDataGenerator::FillInsBuf()
    @     0x7f864654b147  paddle::framework::GraphGpuWrapper::graph_neighbor_sample_v3()
    @     0x7f8646387010  paddle::framework::GraphDataGenerator::GenerateBatch()
    @     0x7f8646385738  paddle::framework::GraphDataGenerator::FillWalkBuf()
    @     0x7f8646357334  paddle::framework::SlotRecordInMemoryDataFeed::Next()
    @     0x7f8646386297  paddle::framework::GraphDataGenerator::FillInsBuf()
    @     0x7f864636aac3  paddle::framework::HogwildWorker::TrainFiles()
    @     0x7f86c9be9fcf  execute_native_thread_routine
    @     0x7f8646387010  paddle::framework::GraphDataGenerator::GenerateBatch()
    @     0x7f86ca991ea5  start_thread
    @     0x7f86c9fb19fd  __clone
    @              (nil)  (unknown)

**Comment by Liwb5** [comment]
是的，目前我们只能支持v100和a100， 消费级显卡应该不行。
