### ISSUE TITLE
AttributeError: module 'paddle.fluid.libpaddle.eager.ops' has no attribute 'unique_with_counts'

### ISSUE THREAD

**Issue by CreamyLong** [PaddlePaddle/PGL#531]
when I run the code provide in 

pgl-2.2.3.post0
paddlepaddle-gpu-2.4.1

**Comment by CreamyLong** [comment]
I download the source code and this error does not happen... 
**So do not just "pip install pgl" directly.** 
The team have no time to update

**Comment by Yelrose** [comment]
When do you trigger these errors? We have replace most paddle.fluid.unique_with_counts with paddle.unique

**Comment by Yelrose** [comment]
> So do not just "pip install pgl" directly.

Maybe you should use ``pip install pgl -U`` to upgrade pgl into 2.2.4  for  ```paddlepaddle >= 2.4``` since many fluid operators have been deduplicated.
