### ISSUE TITLE
PGLBox的镜像可以有ubuntu的版本吗

### ISSUE THREAD

**Issue by mengdeer** [PaddlePaddle/PGL#562]
PGLBox的镜像很好用，但是我们的环境不支持centos，请问下这个镜像可以有ubuntu的版本吗

**Comment by DesmonDay** [comment]
centos镜像是可以在ubuntu机器上使用的，可以直接用我们提供的镜像试试。如果有问题，可以在镜像中执行ldconfig这个命令。
