### ISSUE TITLE
ValueError: (InvalidArgument) argument (position 2) must be list of int, but got memmap at pos 0

### ISSUE THREAD

**Issue by Sky-zzt** [PaddlePaddle/PGL#568]
PGL/examples/deepwalk  
python train.py 跑不动 报错
win 和mac 都试了 

pgl 最新的 2.x
paddle 也是2.x
<img width="992" alt="image" src="https://github.com/PaddlePaddle/PGL/assets/52705155/9c950abe-ee2b-427b-9307-43a5112c3ce0">

**Comment by lyuwenyu** [comment]
PGL指的那个repo ?

**Comment by akari0216** [comment]
把pgl指定安装版本为2.2.4看看（pip install pgl==2.2.4），最新版本是2.2.5，会报这个bug

**Comment by Sky-zzt** [comment]
> 把pgl指定安装版本为2.2.4看看（pip install pgl==2.2.4），最新版本是2.2.5，会报这个bug

<img width="983" alt="image" src="https://github.com/PaddlePaddle/PGL/assets/52705155/80060e1d-59cd-4d1d-9999-0385b0f92575">

**Comment by akari0216** [comment]
paddle版本是多少？我在aistudio上测试的环境是paddle 2.3.2.post112, pgl 2.2.4

**Comment by Sky-zzt** [comment]
> paddle版本是多少？我在aistudio上测试的环境是paddle 2.3.2.post112, pgl 2.2.4

paddlepaddle              2.5.0                  py38_mac    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle

**Comment by akari0216** [comment]
[旧版本安装](https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/pip/linux-pip.html)试试看

**Comment by bobbyxuy** [comment]
model.py中的由原来的：nn.Embedding(num_nodes, embed_size, sparse=sparse, weight_attr=v_emb_attr)改为：nn.Embedding(int(num_nodes), embed_size, sparse=sparse, weight_attr=v_emb_attr)
可正常运行
