### ISSUE TITLE
 【Windows】Could not find a version that satisfies the requirement pgl

### ISSUE THREAD

**Issue by Nihilitior** [PaddlePaddle/PGL#72]
win10
anaconda
python 3.7.1 
paddlepaddle-gpu 1.7.1.post97
使用pip install pgl 提示 Could not find a version that satisfies the requirement pgl
用pip search pgl 提示有pgl(1.1.0)版本
请问是哪里有问题导致无法安装这个包呢QAQ

**Comment by kirayummy** [comment]
PGL暂未有windows的python wheel，建议在linux和mac环境下使用~  :)

**Comment by Yelrose** [comment]
> win10
> anaconda
> python 3.7.1
> paddlepaddle-gpu 1.7.1.post97
> 使用pip install pgl 提示 Could not find a version that satisfies the requirement pgl
> 用pip search pgl 提示有pgl(1.1.0)版本
> 请问是哪里有问题导致无法安装这个包呢QAQ

目前，已经把这个包上传到Pip了。现在支持python3.6 3.7 3.8 windows下的pip install。但是部分的功能，例如多进程相关的代码可能暂时无法使用。样例中大部分不涉及多进程的都是可以跑的。
