### ISSUE TITLE
【windows】pgl    ImportError: DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by yhx0105** [PaddlePaddle/PGL#78]
win10+py 3.6+paddle 1.8.0 +pgl 1.1.0
你好，在pip install pgl成功之后;
import pgl 时 报错   
```
 import pgl.graph_kernel as graph_kernel
ImportError: DLL load failed: 找不到指定的模块。
```
请问该如何解决

**Comment by wangxinxin98** [comment]
你好，请问你的问题解决了嘛，我也遇到了同样的报错

**Comment by Yelrose** [comment]
> 你好，请问你的问题解决了嘛，我也遇到了同样的报错

你这个环境也是一样的妈？

**Comment by Yelrose** [comment]
这边测试了一下，在下面环境都是能跑的。
Win10 + Anaconda + python3.6 + pgl=1.1.0 + paddle 1.8
Win10 + Anaconda + python3.7 + pgl=1.1.0 + paddle 1.8

建议你们使用Anaconda。 有些Windows的环境变量配置，可能比较复杂。

**Comment by wangxinxin98** [comment]
> 你好，请问你的问题解决了嘛，我也遇到了同样的报错
> 
> 你这个环境也是一样的妈？

环境也是一样的

**Comment by wangxinxin98** [comment]
> 这边测试了一下，在下面环境都是能跑的。
> Win10 + Anaconda + python3.6 + pgl=1.1.0 + paddle 1.8
> Win10 + Anaconda + python3.7 + pgl=1.1.0 + paddle 1.8
> 建议你们使用Anaconda。 有些Windows的环境变量配置，可能比较复杂。

好的，谢谢

**Comment by jc-moon** [comment]
一样的错误
 import pgl.graph_kernel as graph_kernel
ImportError: DLL load failed

**Comment by Yelrose** [comment]
解决方案：
1. 查看是否环境变量有缺失，在命令行下echo %PATH% 查看下面路径是否在你的命令行中。

%CONDA_ENV%\Library\usr\bin
%CONDA_ENV%\Library\bin;
%CONDA_ENV%\Scripts;
%CONDA_ENV%\bin

这里CONDA_ENV自行替换成你的anaconda路径。


DLL Failed的问题，基本都是环境变量配置问题，具体可以参考一下博客：

可以参考： 
1. [https://blog.csdn.net/qq_43251358/article/details/93389320](https://blog.csdn.net/qq_43251358/article/details/93389320)
2. [https://blog.csdn.net/qq_23996885/article/details/88713249](https://blog.csdn.net/qq_23996885/article/details/88713249)

**Comment by qinwenxue** [comment]
windows 10 + pip 安装paddle + pgl，遇到同样的错误，环境变量设置无误。后来用anaconda安装一次也是同样的问题。
后来解决办法是：下载depends软件，打开graph_kernel.cp37-win_amd64.pyd，提示缺少vc的一个dll，最后安装vc_redist.exe来解决
希望对大家有帮助。
