### ISSUE TITLE
请问STGCN的样例数据在哪下载？

### ISSUE THREAD

**Issue by edencfc** [PaddlePaddle/PGL#95]
PGL/examples/stgcn中没有提供数据下载方式。

**Comment by Liwb5** [comment]
谢谢提醒. 我已经重新上传了一个样例数据集.请重新拉取main分支代码. 
ps: 国际大数据竞赛的基线系统也是用PGL的stgcn模型实现的, 也可以参考一下. 
链接: https://aistudio.baidu.com/aistudio/projectdetail/457185

**Comment by edencfc** [comment]
好的，谢谢。
