### ISSUE TITLE
GAT 带权重边

### ISSUE THREAD

**Issue by KaiyuanGao** [PaddlePaddle/PGL#97]
请问如果想要在GAT中加入graph边权重的信息，应该在哪里修改呢？

谢谢！

**Comment by Yelrose** [comment]
https://github.com/PaddlePaddle/PGL/blob/main/pgl/layers/conv.py#L121

可以参考这里，然后修改send函数把边特征考虑进去，例如


```
def send_attention(src_feat, dst_feat, edge_feat):
   
        output = src_feat["left_a"] + dst_feat["right_a"]
        output = fluid.layers.leaky_relu(
            output, alpha=0.2)  # (num_edges, num_heads)
        return {"alpha": output, "h": src_feat["h"] * edge_feat["weight"]}
```

**Comment by KaiyuanGao** [comment]
> https://github.com/PaddlePaddle/PGL/blob/main/pgl/layers/conv.py#L121
> 
> 可以参考这里，然后修改send函数把边特征考虑进去，例如
> 
> ```
> def send_attention(src_feat, dst_feat, edge_feat):
>    
>         output = src_feat["left_a"] + dst_feat["right_a"]
>         output = fluid.layers.leaky_relu(
>             output, alpha=0.2)  # (num_edges, num_heads)
>         return {"alpha": output, "h": src_feat["h"] * edge_feat["weight"]}
> ```

感谢！

**Comment by KaiyuanGao** [comment]
你好，再请问下 gat的分布式训练有demo吗？

**Comment by Yelrose** [comment]
这个你可以找分布式graphsage，然后把里面的graphsage层替换成gat就好了
